### ISSUE TITLE
WoW 1.12.1 Lightning/Alpha bug (Game is way too bright)

### ISSUE THREAD

**Issue by XXXBold** [Joshua-Ashton/d9vk#314] opened 2019-08-20 18:43 UTC
### Software information
WoW Classic Client (1.12.1)
### Problem description
The game looks very bright and it's not possible to change the alpha ingame (slider is greyed out). Using Wine's d3d9, it looks fine.
D9VK:
![wow_d9vk](https://user-images.githubusercontent.com/30773753/63374758-02af9a80-c37a-11e9-8bd7-892151ef4be9.png)
D3D9:
![wow_d3d9](https://user-images.githubusercontent.com/30773753/63374777-0b07d580-c37a-11e9-9654-1618a73177a3.png)

### System information: 
- OS: Linux Mint 19.1 Cinnamon
- GPU: AMD Radeon R9 290X
- Driver: mesa 19.2-git (oibaf ppa)
- Wine version: 4.11 (Steam Proton 4.11.2)
- DXVK version: d9vk-v0.90-1653-g1c5ce36e (included in proton)

Maybe this is the same as https://github.com/Joshua-Ashton/d9vk/issues/219 (The screenshots below)

### Log files
- d3d9.log:
[WoW_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3522087/WoW_d3d9.log)

Let me know if you need more information.

Edit: If this was already resolved, I'm sorry. But I'm kinda confused  with the d9vk versions...

**Comment by K0bin** [comment] 2019-08-20 18:56
This is probably caused by fixed function lighting which has been implemented since the last release.

Can you try #716 from this page https://git.froggi.es/joshua/d9vk/pipelines?

**Comment by XXXBold** [comment] 2019-08-20 18:59
> This is probably caused by fixed function lighting which has been implemented since the last release.
> 
> Can you try #716 from this page https://git.froggi.es/joshua/d9vk/pipelines?

I can try, hope I'm able to build it :P

**Comment by XXXBold** [comment] 2019-08-20 19:49
Seems I can't install it properly. 
I downloaded/extracted it. Now I tried to install it, I run this in a terminal:
`export WINEPREFIX="/home/simon/.local/share/Steam/steamapps/compatdata/pfx"
./setup_dxvk.sh install`

which did set up the stuff, no error reported etc.

I made a script to run WoW from the same prefix:
`#!/bin/sh
export STEAM_COMPAT_DATA_PATH=$HOME/.local/share/Steam/steamapps/compatdata/
export WINEPREFIX="/home/simon/.local/share/Steam/steamapps/compatdata/pfx"
export PROTON_USE_D9VK=1
export WINEARCH=win64

MY_RUN_EXE_PATH="/media/simon/SSD2/World of Warcraft 1.12.1/WoW.exe"
PROTON_RUN_DIR="$HOME/.local/share/Steam/steamapps/common/Proton 4.11"

"$PROTON_RUN_DIR/proton" run "$MY_RUN_EXE_PATH"`

It was starting again, but d9vk version was reported as the same as before (d9vk-v0.90-1653-g1c5ce36e) and issue was still present.

**Comment by XXXBold** [comment] 2019-08-21 18:11
Update: could finally install it, but needed to replace the original files in the proton directory, because the ones in the wine prefix always have been overwritten...

Anyway, the bug is not present with this version anymore, ty for fixing, nice work!

Now I get another bug (using #716 build), objects in distance sometimes just occur black: 
![wow_black_bug](https://user-images.githubusercontent.com/30773753/63456707-0c4f0600-c43f-11e9-9866-4f3981ce7437.png)
![wow_black_bug2](https://user-images.githubusercontent.com/30773753/63456713-0fe28d00-c43f-11e9-8338-2ee7491ba40d.png)

**Comment by K0bin** [comment] 2019-08-21 18:40
We need an apitrace to debug this issue.

**Comment by XXXBold** [comment] 2019-08-21 19:21
Never done that. Hopefully I made it correct :P

Here you can find it (compressed as 7z): https://lots-of.space/s/mc7xnZyjjbLS4R9

**Comment by Joshua-Ashton** [comment] 2019-08-22 04:37
The trace renders fine for me as of 38317670396f3699b86311eb20d74e827a8f2cc5

Going to close this, feel free to re-open if there is something I missed :)

**Closed by Joshua-Ashton** 2019-08-22 04:37 UTC
