### ISSUE TITLE
Witcher has (many) lighting artefacts and glitches.

### ISSUE THREAD

**Issue by RobertZenz** [Joshua-Ashton/d9vk#411] opened 2019-10-05 12:15 UTC
"The Witcher: Enhanced Edition" works but suffers from various lighting issues. One of them is that interiors are not correctly lit, for example here in the crypt:

![witcher lighting artefact](https://user-images.githubusercontent.com/611377/66254609-0dcb5800-e779-11e9-9a03-cf482a0cbaa4.jpeg)

As you can see, the floor tile is not being correctly lit, if I move forward a few centimeters it will get differently lit.

In other instances the lighting on objects changes with instances (for example the goose change how they are lighted depending on distance it seems, so it might have something to do with some LOD implementation). Also some buildings interiors are brightly lit while posters in the city are pitch black.

I can provide you with a copy of the game on GOG and save games showcasing the issue if you want.

### Software information
 * Use the release package and extracted the dll files into the same directory as the exe file of the game and added overrides for them. Is this the correct way to get it working (as I just saw the important note on the last release page) or did I miss something?
 * The Witcher: Enhanced Edition (from GOG)
 * All settings to maximum (changing the lighting settings doesn't change the problems).

### System information

 - GPU: nVidia 1050Ti
 - Driver: 418.56
 - Wine version: 4.17
 - DXVK version: 0.22

### Apitrace file(s)

 - [trace](https://bonsaimind.org/tmp/witcher.trace.tar.xz)

### Log files

 - [d3d9.log](https://bonsaimind.org/tmp/witcher_d3d9.log)

**Comment by Joshua-Ashton** [comment] 2019-10-05 22:28
Looks like the issue is baked into your trace.

Are you using native d3dcompiler and d3d9x?

**Comment by NerosTie** [comment] 2019-10-05 22:34
Can you upload you save file please?

**Comment by RobertZenz** [comment] 2019-10-06 09:03
> Are you using native d3dcompiler and d3d9x?

If you mean and installed DirectX package, then the answer is No (as said I above, I'm unsure about exactly that). Otherwise, how do I check that?

 > Can you upload you save file please?

[Sure](https://bonsaimind.org/tmp/witcher-save.tar.xz).

 > btw your driver is a little bit old now

Yes, there don't seem to be updates for my system anymore (Ubuntu 16.04), or at least none that are packaged, so it's going to stay that way until I upgrade (which is planned for the end of 2021).

**Comment by NerosTie** [comment] 2019-10-06 12:34
I see no difference with or without d9vk (#894):

https://imgur.com/RfA8sa9

But when I retrace your trace, I can see the glitch.

**Comment by edmondo** [comment] 2019-10-06 12:38
This youtube video shows the exactly same issue on windows:
https://www.youtube.com/watch?v=YrBoax13By4&feature=youtu.be&t=1355

Also on my setup it looks the same:
![2019-10-06-124523_1920x1080_scrot](https://user-images.githubusercontent.com/1729650/66269268-df1bb300-e846-11e9-9b49-cc481a46332a.png)

Let's close this issue, since the bug seems to be in the game and not related to d9vk.

**Comment by Joshua-Ashton** [comment] 2019-10-06 12:39
This is a setup issue then.

You can use winetricks to install d3d9x and the different versions of d3dcompiler.

I'd also reccomend to update your suuuper old driver 🐸

**Closed by Joshua-Ashton** 2019-10-06 12:39 UTC

**Comment by RobertZenz** [comment] 2019-10-06 13:22
Uhm, can we add that requirement then to README and maybe the setup script, please? Because I could find it in neither of them and as you've pointed out in the release notes, that seems kinda important.

Also, crap, after some more trial and error I figured out that Witcher is broken with d3dx9_43, it works with d3dx9_35 without any of the issues I mentioned. So sorry to bother you with that.

**Comment by Joshua-Ashton** [comment] 2019-10-06 16:30
No. I shouldn't have to put workarounds for Wine bugs in the project. Their d3d9x and d3dcompiler implementations been broken and unusable since forever.

**Comment by RobertZenz** [comment] 2019-10-06 16:32
Huh? That I don't get, adding a note to the README should spare you some trouble down the road...whether to add it to the install script or not is debatable, though.

**Comment by K0bin** [comment] 2019-10-06 16:33
![grafik](https://user-images.githubusercontent.com/1131720/66272276-d7203b00-e867-11e9-86fd-578a73f1b8fe.png)

**Comment by Joshua-Ashton** [comment] 2019-10-06 16:35
Stuff in releases is there only so you can actually use the project.
It's not a solution or something I want to rely on.
It's not my bug that the Wine implementations are broken in every game that uses them.

**Comment by Joshua-Ashton** [comment] 2019-10-06 16:35
-> https://bugs.winehq.org
