### ISSUE TITLE
All text disappearing

### ISSUE THREAD

**Issue by Mantas-2155X** [Joshua-Ashton/d9vk#62] opened 2019-05-02 12:07 UTC
### Software information
- Game: Garry's Mod
- OS: Ubuntu 19.04

### System information
- GPU: GTX 750 Ti
- Driver: 430.09
- Wine version: 4.2
- D9VK version: Latest master build (Latest commit 4957fec), happened with previous builds aswell.

### Apitrace file(s)
- Happens at unpredictable times, hopefully the log files will suffice to find what is the issue.

### Log files
- d3d9.log: https://pastebin.com/UNxtCaJg
- dxgi.log: https://pastebin.com/DXAKSVPB

Randomly while playing the game, out of nowhere all text disappears. Tools, weapons, spawn menu, chat, console, menu. Only text on images loads (obviously). After a while (2-15mins), the text appears back and everything is normal.
Right now I don't have a picture, but if it happens again I'll upload it here.

This is my first 'issue', sorry if I'm doing this wrong.

**Comment by Joshua-Ashton** [comment] 2019-05-02 12:32
Can you try adding `+mat_disable_d3d9ex 1 -nod3d9ex` to the Garry's Mod command line and see if that rectifies the issue? If it does, it confirms its part of a greater issue I am already aware of.

**Comment by Mantas-2155X** [comment] 2019-05-02 12:38
My current launch options are `"-dxlevel " "90" "-nod3d9ex" "-freq " "77" "-threads " "4"`. 
`mat_disable_d3d9ex` is set to 1 from my autoexec file and seems to work according to the console.

**Comment by Joshua-Ashton** [comment] 2019-05-02 12:50
Is anything fixed by `+mat_queue_mode 0 -threads 1`?

**Comment by Mantas-2155X** [comment] 2019-05-02 12:53
I'll try that, play for the day and will get back to you tomorrow (or earlier if it happens again)

**Comment by Joshua-Ashton** [comment] 2019-05-02 12:54
Oh, does it not occur straight away? Interesting. I'll try it when I get back (on amdvlk.)
I only tested Garry's Mod 10 before for some reason 🐸

**Comment by Mantas-2155X** [comment] 2019-05-02 12:58
Yeah, it only happens once or twice a day if I play for long periods of time. I mostly only play on one server and it runs the same map all the time `rp_downtown_tits_v2` but I don't think that's the issue.

**Comment by Joshua-Ashton** [comment] 2019-05-02 13:00
> `rp_downtown_tits_v2`

Nice map name. 🐸

**Comment by Joshua-Ashton** [comment] 2019-05-02 13:05
Looks like it wants a d3d format hack of SSAA, I haven't seen that one before.

**Comment by Mantas-2155X** [comment] 2019-05-05 15:07
UPDATE:
* `-threads` does not seem to affect the issue.
* Today the bug happened again with `mat_queue_mode 2` and `gmod_mcore_test 1`. After turning them both to 0, the bug stopped (only took around 10s, when usually it takes 10min to go away). This could be a coincidence so I'll wait for it to happen again and see if the issue can be fixed this way.

**Comment by Mantas-2155X** [comment] 2019-05-06 16:23
UPDATE 2:
* Seems like `mat_queue_mode 2` is not an issue as it just happened with it set to 0
* After setting `gmod_mcore_test` to 0, the issue was fixed after around 5 secs.

Managed to get a picture of what happens: https://i.gyazo.com/8312ba77ba52b9d5b3d41008e467d7b7.png

I will now try playing with `gmod_mcore_test 0` (and `mat_queue_mode 0`)to see if the issue happens again.

**Comment by Mantas-2155X** [comment] 2019-05-12 21:59
Another update..
Seems like the bug happens with `mat_queue_mode 0` and `gmod_mcore_test 0`. They are unrelated.

Also, I've just built the latest version and it seems like the bug happens excessively and very commonly, almost 5 minutes after playing.

**Comment by willox** [comment] 2019-05-29 21:56
@Joshua-Ashton if you can specify what you mean by `a d3d format hack of SSAA` I may be able to provide some insight as a developer for GMod.

**Comment by Joshua-Ashton** [comment] 2019-05-29 22:12
Ah hello, I too have suffered with the pain of working with Source for a significant portion of my life. :frog:

NVIDIA transparency supersampling (SSAA). I'm fairly sure this isn't the issue, as it appears to be queried in regular Source and I just say I don't support it, and I checked what Source does when I say I don't support it -- it just doesn't use it.

Not sure where the issue actually lies here -- would be nice to know if this is still occurring with my recent texture rewrites.

I'm not at a PC so I can't check, GMod is D3D9Ex these days, right?

**Comment by willox** [comment] 2019-05-29 22:18
I can't remember if it defaults to d3d9ex, but it can definitely function as d3d9 OR d3d9ex (you can force it to d3d8, but we're not supporting that.)

I fixed an OpenGL build issue recently on our x86-64 branch where a mip filter was being specified for textures without mipmaps, the result was text not rendering. Do you think that could be related? The patch for that is only on the x86-64 branch, not the default one.

**Comment by Joshua-Ashton** [comment] 2019-05-29 22:21
Mip filters should be valid on textures without mipmaps (at least in D3D9 anyways,) so I don't think that would be the issue.

**Comment by Mantas-2155X** [comment] 2019-05-29 22:22
I haven't had the chance to test any newer builds, prep for exams taking all my time.
Hopefully tomorrow or this weekend I should be able to play for the entire day and see if the issue happens with the latest commits

**Comment by willox** [comment] 2019-05-29 22:24
The mip filters thing was only an issue in our native Linux builds. It'd be nice to figure this out, but without a way to reproduce this issue there's not much I can do.

I can double check exactly what GMod is doing with the NVIDIA transparency supersampling if you can tell me how it is queried.

**Comment by Joshua-Ashton** [comment] 2019-05-29 22:36
Again, pretty sure it's unrelated, but if you're interested.

Check the ``if ( pCaps->m_VendorID == VENDORID_NVIDIA )`` section in shaderdevicedx8.cpp. The code that queries for SSAA support is in there, along with querying for regular ATOC (Alpha to Coverage)

**Comment by Joshua-Ashton** [comment] 2019-05-29 22:37
fwiw The branch I have here queries the support for it then doesn't use it anyway :stuck_out_tongue:

**Comment by willox** [comment] 2019-05-29 22:47
GMod doesn't do anything unique in that code.

Looking over the two Gyazo images, it feels like the procedural textures used by the font renderer are at fault. I've never seen this issue happen on a Windows client before though. I don't think those textures are ever dropped during a session (there's no ref-counting on fonts or anything like that), so I can't really explain it.

I'll probably just wait to see if Mantas is still running into this problem.

**Comment by willox** [comment] 2019-05-29 22:49
There are those 5 bullet icons rendering in the broken image. They make me suspicious, but I can't think of a good reason for it to happen.

**Comment by Joshua-Ashton** [comment] 2019-05-29 22:53
I actually had a similar issue on regular Windows years ago when I used to play GMod, where not only would text dissapear, but also every entity. Wonder if its a related issue.

**Comment by Mantas-2155X** [comment] 2019-05-29 22:56
The 5 bullet icons pretty sure are part of an image, which doesn't disappear like the one on the top right (red blimp)

**Comment by Mantas-2155X** [comment] 2019-06-26 07:30
After playing again a week back, the issue happened again and in the logs I saw something about memory allocation.
Anyway, I have purchased a new GPU now and stopped playing GMod so I am not sure if the issue is still valid with the new commits.

**Comment by Joshua-Ashton** [comment] 2019-09-20 15:05
Played Garry's Mod for a few hours with d9vk with no issue.

**Comment by Joshua-Ashton** [comment] 2019-11-27 15:42
I've played hours of Garry's Mod with D9VK since (mainly TTT) and haven't seen this.

I'm going to assume this is no longer an issue - although I couldn't repro it in the first place :-/

If you manage to repro the issue please do let me know and I can re-open this.
If you can, an apitrace would be ideal if you can find me a solid case.

**Closed by Joshua-Ashton** 2019-11-27 15:42 UTC
