### ISSUE TITLE
World of Warcraft Wrath of The Lich King : No Cursor and Texture Problem

### ISSUE THREAD

**Issue by XEmpty** [Joshua-Ashton/d9vk#174] opened 2019-06-16 17:30 UTC
Game have problem with correct load a texture (on spell bars  (interface) and on some object i see black ).

And most problem for me it's no cursor in game. If enable / disable hardware cursor ( still don't work ). 

I test game with d3d9.dll from dgvoodo and it's works but with less performance.

### Software information
World of Warcraft 3.3.5a (Lich King)

### System information
- GPU: GTX 960 4GB
- Driver: 430.26-2
- Wine version: 4.9
- DXVK version: 0.12

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log: None
- dxgi.log: None
- d3d9.log : Attach
[Wow_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3294378/Wow_d3d9.log)
![Screenshot_20190624_134956](https://user-images.githubusercontent.com/8018061/60016678-29f23000-9687-11e9-800d-d272e6eaa3c3.png)

Edit : Game running great expect this 2 bugs... Even dgvoodo can't make smooth game run like pure d9vk. Will be nice to quick solve this problems. I can testing patches any time.

**Comment by donescopeta** [comment] 2019-06-25 18:06
I have the same problem.

**Comment by neVERberleRfellerER** [comment] 2019-06-25 21:04
Is this duplicate of https://github.com/Joshua-Ashton/d9vk/issues/17 (it mentions missing cursor and missing sprites) ?

**Comment by XEmpty** [comment] 2019-06-26 07:10
Yea, like on screen. Missing cursor & Sprites.

**Comment by XEmpty** [comment] 2019-06-29 16:23
I saw something... when i have enabled hardware cursor then mouse point it's on top left corner and is pin here. When i disable hardware cursor then i can move mouse normal, but it's "invisible" , sprites on spell bars to, and some things like glow on target, minimap, buffs, dbeuffs and maybe many more. Maybe it's only problem with shaders? Software hardware work but isn't visible. Like anything else .

**Comment by Joshua-Ashton** [comment] 2019-07-03 22:12
Implemented hardware cursor: https://github.com/Joshua-Ashton/d9vk/commit/1e8fdd59d2f3e8266af469319a7543741b035299

**Comment by XEmpty** [comment] 2019-07-04 11:37
No sprites but cursor working good. (using last commit) 

![image](https://user-images.githubusercontent.com/8018061/60663906-cf17c000-9e60-11e9-80d4-6267d55a9d19.png)

**Comment by Joshua-Ashton** [comment] 2019-07-04 12:41
Not sure what you mean by no sprites, can you point that out to me?

**Comment by XEmpty** [comment] 2019-07-04 13:27
Sure, if u see on above screenshot. Black square on bottom bars and on right side a items with number . Here must be icon. Like on rest of things . But on d9vk they don't display correct. Sometimes some of them looks like empty square, but sometimes it's incorrect icon from different things... 

Problem : 

### Left Side (Spell Book)
![D9VK-1](https://user-images.githubusercontent.com/8018061/60669795-7b60a300-9e6f-11e9-98e3-af4fa2a1de83.jpg)
![OPENGL-1](https://user-images.githubusercontent.com/8018061/60669805-81568400-9e6f-11e9-8e87-45d9ef31bbf0.jpg)

### Right Top Corner (Spell Buffs)
![D9VK-2](https://user-images.githubusercontent.com/8018061/60669796-7bf93980-9e6f-11e9-8ae2-e18ad12600c7.jpg)
![OPENGL-2](https://user-images.githubusercontent.com/8018061/60669807-81ef1a80-9e6f-11e9-839b-cfe88cd66129.jpg)

### Cursor on Spell Bar (Bottom)
![D9VK-3](https://user-images.githubusercontent.com/8018061/60669797-7bf93980-9e6f-11e9-9547-806cc12c8e12.jpg)
![OPENGL-3](https://user-images.githubusercontent.com/8018061/60669809-81ef1a80-9e6f-11e9-9ad9-3a8fb8154baf.jpg)

### Aura isn't visible on D9VK (that glow circle on ground)
![OPENGL-AURA](https://user-images.githubusercontent.com/8018061/60669812-83b8de00-9e6f-11e9-8fb8-e002fab28b86.jpg)


And it's more problem with visuals. On some location it's black or different sky. I make for u more ss if u want. I don't know how to help u in best way. 

Logs :
[Wow_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3359426/Wow_d3d9.log)
[Wow_d3d11.log](https://github.com/Joshua-Ashton/d9vk/files/3359427/Wow_d3d11.log)
[Wow_dxgi.log](https://github.com/Joshua-Ashton/d9vk/files/3359428/Wow_dxgi.log)

**Comment by XEmpty** [comment] 2019-07-08 08:09
When i install mesa-git icons are showing up after /reload when i put spells on bars. Before this doesn't working because i try this method.  And icons from spell bar showing in spell book... strange. 

I know one thing when u minimize wow on loading screen (first game load) and u don't have "window" mode, then all ui it's real mess like black icons, strange icons etc..

**Comment by Grixin** [comment] 2019-07-10 05:21
I can also verify the issue. With 0.13 release hardware cursor is present. However I am also missing spells on bars (not all). Some items in my bags are also black squares or invisible. Otherwise great performance. ~200fps at 1440p

**Comment by Riesi** [comment] 2019-07-10 14:20
Here crborga's apitrace from #156, so that it doesn't get lost.
It shows the the icon issue when replayed with d9vk:
https://mega.nz/#!2h5GyAiA!Ef9C737YEY_XDQtKyAa2YKxubZ3_jfAwkAob9L3_t88

**Comment by XEmpty** [comment] 2019-07-10 18:17
I try make own apitrace log but after that i don't get any error on "detrace" it's like normal log from d9vk   .

**Comment by BLaDZer** [comment] 2019-11-06 17:23
Great news! Most of texture glitches successfully fixed in v0.30 except of minimap issue that still rendering outside the box. 

How it looks with d9vk and how should be:

![screenshot_2019-11-06_21-16-15](https://user-images.githubusercontent.com/13044587/68321578-645ee580-00db-11ea-9595-c1e4337a1dc6.png)
![screenshot_2019-11-06_21-19-14](https://user-images.githubusercontent.com/13044587/68321588-69bc3000-00db-11ea-8938-f4100022d802.png)

**Comment by Joshua-Ashton** [comment] 2019-12-18 01:14
This seems to render fine now based on the trace, can people confirm?

**Comment by BLaDZer** [comment] 2019-12-18 17:41
I can confirm that everything looks like it should be. Also minimap issue was fixed too (tested with DXVK 1.5).

Thank you very much @Joshua-Ashton !

**Closed** 2019-12-18 17:57 UTC
