### ISSUE TITLE
Skyrim crashes on launch

### ISSUE THREAD

**Issue by qsniyg** [Joshua-Ashton/d9vk#105] opened 2019-05-14 01:40 UTC
Running Skyrim without D9VK works fine (of course). With D9VK, it crashes. I thought this was because of ENB (as ENB makes Skyrim SE and Fallout 4 crash under DXVK), so I renamed the DLL (d3d9.dll to d3d9_enb.dll), but with the same result (crash).

I created an apitrace without D9VK, but replaying it under D9VK has no issues, and renders as it should without crashing.

I then created an apitrace under D9VK, which of course crashed. Replaying that apitrace crashes as well, both under D9VK and vanilla wine.

This is under a clean WINEPREFIX by the way. The only DLL overrides were set by the install script. The only other change I made was to have a virtual desktop.

### Software information
Skyrim, not modded, no SKSE (although the issue also appears with SKSE).

### System information
- GPU: GTX 660 TI
- Driver: 418.56
- Wine version: 4.6 (staging)
- D9VK version: c8fb2d569675cd7ef37712b0b2d4efe53db752c6 (but also with previous versions)

### Apitrace file(s)

[broken_trace.zip](https://github.com/Joshua-Ashton/d9vk/files/3175447/broken_trace.zip) (This trace was done with D9VK, it crashes)
[good_trace.zip](https://github.com/Joshua-Ashton/d9vk/files/3175448/good_trace.zip) (This trace was done without D9VK, and runs fine under D9VK.)

### Log files
[TESV_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3175441/TESV_d3d9.log)
- d3d11.log: Empty
- dxgi.log: Empty

**Comment by Joshua-Ashton** [comment] 2019-05-14 21:18
I am aware of this, currently it crashes due to a WineVulkan bug...

Can you verify it is the same issue and try playing fullscreen which should correct the issue.

**Comment by qsniyg** [comment] 2019-05-15 22:33
Thanks for replying. Indeed, setting "bFull Screen=1" fixed it.

**Comment by Joshua-Ashton** [comment] 2019-05-16 00:11
Yeah this isn't my issue. I'll keep it open though, but I've nagged the appropriate people.

**Comment by coreyoconnor** [comment] 2019-05-26 18:07
I've also encountered a crash launching TESV. 

* built from HEAD. 
* wine staging 4.8

I haven't done any comparison against above. No idea if this is caused by the same. Including the backtrace. Can collect other info if of interest.

~~~
Unhandled exception: assertion failed in 32-bit code (0x68001232).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:68001232 ESP:0032ed7c EBP:0032ed80 EFLAGS:00000246(   - --  I  Z- -P- )
 EAX:00000000 EBX:00000002 ECX:0032ed80 EDX:00000000
 ESI:00000008 EDI:00000000
Stack dump:
0x0032ed7c:  68243a10 00000000 00000000 00000000
0x0032ed8c:  00000000 00000000 00000000 00000000
0x0032ed9c:  00000000 00000000 00000000 00000000
0x0032edac:  00000000 00000000 00000000 ffffffec
0x0032edbc:  00000001 00000000 00000000 fffffff8
0x0032edcc:  00000001 fffffff0 00000001 fffffff4
Backtrace:
=>0 0x68001232 length_mismatch+0xffffffff() in ld-linux.so.2 (0x0032ed80)
  1 0x68243a10 int_mallinfo+0xffffffff() in libc.so.6 (0x0032ed80)
  2 0x68244c07 int_mallinfo+0xffffffff() in libc.so.6 (0x0032f018)
  3 0x6a27b172 (0x0032f018)
  4 0x6a2789d4 (0x0032f0f8)
  5 0x6a0ce3a5 _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc+0xffffffff() in d3d9 (0x0032f1c8)
  6 0x6a0ce750 _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc+0xffffffff() in d3d9 (0x0032f228)
  7 0x6a0c3b56 _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc+0xffffffff() in d3d9 (0x0032f288)
  8 0x6a0c5293 _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc+0xffffffff() in d3d9 (0x0032f438)
  9 0x6a0c557d _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc+0xffffffff() in d3d9 (0x0032f468)
  10 0x6a0aa8e7 _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc+0xffffffff() in d3d9 (0x0032f788)
  11 0x6a0aaffc _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc+0xffffffff() in d3d9 (0x0032f7c8)
  12 0x00cd8b74 EntryPoint+0xffffffff() in tesv (0x1085b7bc)
~~~

(yea yea 32bit.. I don't feel like buying skyrim again haha)

**Comment by qsniyg** [comment] 2019-06-04 16:48
@coreyoconnor Try using wine-staging 4.6 instead. 4.8 and 4.9 for some reason seems to have broken modded skyrim for me.

**Comment by CartoonFan** [comment] 2019-06-10 08:00
Fallout: New Vegas also crashes if windowed, but works fine in fullscreen.
The terminal also says: "terminate called after throwing an instance of 'dxvk::DxvkError'" after the crash.
I'm using the latest master and Wine TKG 4.9

[FalloutNV_d3d9_windowed.log](https://github.com/Joshua-Ashton/d9vk/files/3271110/FalloutNV_d3d9_windowed.log)

**Comment by l12436** [comment] 2019-07-15 01:30
I have success launch TESV skyrim these day. Having some bug, but not crash on startup.

**Comment by Joshua-Ashton** [comment] 2019-07-15 01:32
> I have success launch TESV skyrim these day.

There's a WineVulkan patch to make windowed mode work...

> Having some bug, but not crash on startup.

Details?????????????????????????????????

**Comment by l12436** [comment] 2019-07-15 01:38
> > I have success launch TESV skyrim these day.
> 
> There's a WineVulkan patch to make windowed mode work btw
> 
> > Having some bug, but not crash on startup.
> 
> Details please?

You mean the BUG?
I can make some screenshot, I am still find out how to use apitrace in wine.

**Comment by Joshua-Ashton** [comment] 2019-07-15 01:49
If you can screenshot it, that would be great at the moment. I own the game so I can try and replicate your issues myself :-)

**Comment by l12436** [comment] 2019-07-15 02:03
> If you can screenshot it, that would be great at the moment. I own the game so I can try and replicate your issues myself :-)

After a quick check. It seems after update d9vk  yesterday. The map issue seems gone. maybe....

I may updload a screenshot If I have notice something weird.

The bug I notice is the map call out by M key. sometimes It render darker than I remember.

**Comment by l12436** [comment] 2019-07-18 14:49
since I update to commit 6a98f5bb1f8fce2fbc35b2f9c037faee7b77f453
skyrim become to this.

![unknown](https://user-images.githubusercontent.com/2596649/61467473-421b4d80-a9ae-11e9-9c37-a25fde17dff7.png)

**Comment by Joshua-Ashton** [comment] 2019-07-18 16:46
That should be fixed *by* that commit. Please check again.

**Comment by Joshua-Ashton** [comment] 2019-07-20 16:38
Given that there's a patch for child window stuff available now, I'm going to close this.

**Closed by Joshua-Ashton** 2019-07-20 16:38 UTC
