### ISSUE TITLE
Call of Juarez Gunslinger → everything is black

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#238] opened 2019-07-15 21:12 UTC
With d9vk
![](https://i.imgur.com/wYsygTS.png)
When I hit "escape", I have this:
![](https://i.imgur.com/R7LjHWr.jpg)

### System information
GPU: Nvidia GT 730M
Driver: 430.26-9
Wine version: Proton 4.2
DXVK version: 0.13

### Apitrace file(s)
https://mega.nz/#!bjQExY5D!XR7yAofHGhtnCHbukLDA5uBiVBs0tmU1WAdBq0VfM34

### Log files
d3d: [CoJGunslinger-204450.log](https://github.com/Joshua-Ashton/d9vk/files/3394221/CoJGunslinger-204450.log)

**Comment by NerosTie** [comment] 2019-07-17 18:29
This issue exists only when the option "Textures' quality" is set to "high".

**Comment by K0bin** [comment] 2019-07-17 18:48
Your trace replays fine with D9VK. Please retest the game with the latest master.
If you need a build: https://git.froggi.es/joshua/d9vk/pipelines

**Comment by NerosTie** [comment] 2019-07-17 19:06
Tested with the latest master. The issue still exists when "Textures' quality" is set to "high".
Plus, now, the screen is black on the first screen "hit a button to continue" and on the loading screens.

**Comment by NerosTie** [comment] 2019-07-17 21:38
@Joshua-Ashton It shouldn't be closed, the main issue is not fixed.

**Comment by Joshua-Ashton** [comment] 2019-07-17 23:44
It was closed when I merged that patch. The issue is still occurring on master?

**Comment by K0bin** [comment] 2019-07-18 00:06
I guess I misunderstood you. The apitrace renders perfectly fine with D9VK. Was it made with the problematic graphic setting?

If it was I might need a D9VK trace again.

**Comment by Joshua-Ashton** [comment] 2019-07-18 10:24
I played back your trace and it renders fine for me -- would you be able to provide a d9vk trace? Cheers.

**Comment by NerosTie** [comment] 2019-07-18 12:21
@Joshua-Ashton 
> The issue is still occurring on master?

The regression (when you are on loading screens) is fixed, but not the black screen when your are in the game, which was not related to the regression.

@K0bin 

> Was it made with the problematic graphic setting?

Yes.

@Joshua-Ashton 

> would you be able to provide a d9vk trace?

apitrace with d9vk + the problematic graphic setting:
https://mega.nz/#!WuRmwCgS!HISvR_I2V-LB3eqeq4R5tm7F0fQ9YTdr9ipETY-GpsM

**Comment by Joshua-Ashton** [comment] 2019-07-18 12:36
Thanks, can replicate with this.

**Comment by K0bin** [comment] 2019-07-18 13:11
Can you upload the d3d9 logs from playing the game with D9VK?

**Comment by Joshua-Ashton** [comment] 2019-07-18 13:21
Can you also try running with

PROTON_FORCE_LARGE_ADDRESS_AWARE=1

**Comment by NerosTie** [comment] 2019-07-18 14:44
For both: D9VK + PROTON_FORCE_LARGE_ADDRESS_AWARE=1

@K0bin 
[CoJGunslinger_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3407032/CoJGunslinger_d3d9.log)

@Joshua-Ashton 
https://mega.nz/#!fvYWlS4Q!sclDK38sJCoyw6gca6upm7n4qQWNtlUbYStVaGl4J7M

**Comment by Joshua-Ashton** [comment] 2019-07-18 17:15
Can you try the https://github.com/Joshua-Ashton/d9vk/tree/d3d9-memory-tracking branch

Build should be on here when it's done.
https://git.froggi.es/joshua/d9vk/-/jobs/693

**Comment by K0bin** [comment] 2019-07-18 18:46
Great that it works. I'll just drop this here as a reminder for us:

We still need to fix locking the same buffer/image multiple times:
![grafik](https://user-images.githubusercontent.com/1131720/61483244-b64cf580-a99c-11e9-86fc-5ce1cc42091b.png)

Right now it kinda works for some reason but we should handle that properly.

I've tested it with Windows D3D9 and that seems to return the same pointer every time regardless of the Offset. This isn't what happens in the trace though (WineD3D trace).

**Closed** 2019-07-18 20:51 UTC
