### ISSUE TITLE
The Elder Scrolls IV: Oblivion launches with a black screen

### ISSUE THREAD

**Issue by Managor** [Joshua-Ashton/d9vk#88] opened 2019-05-10 04:32 UTC
[Oblivion_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3164894/Oblivion_d3d9.log)

[steam-22330.log](https://github.com/Joshua-Ashton/d9vk/files/3164895/steam-22330.log)

Apitrace: https://drive.google.com/open?id=1tUxJhaZIX-j2PBKrU9gchtSf_YMfeFiL

### Software information
The Elder Scrolls IV: Oblivion

### System information
- GPU: Nvidia 1060 6G
- Driver: 430.09 
- Wine version: 4.3
- D9VK version: 0.10 (43e5332)

### Apitrace file(s)
https://drive.google.com/open?id=1tUxJhaZIX-j2PBKrU9gchtSf_YMfeFiL

**Comment by Joshua-Ashton** [comment] 2019-05-10 07:22
Duplicate of #60

**Closed by Joshua-Ashton** 2019-05-10 07:22 UTC
