### ISSUE TITLE
HITMAN Blood Money - Multiple Issues

### ISSUE THREAD

**Issue by VortexAcherontic** [Joshua-Ashton/d9vk#157] opened 2019-06-09 14:03 UTC
In HITMAN Blood Money is a lot of stuff missing, probably because of Shader Model 3 which is afaik not fully supported by d9vk 0.12.

Here is what is is missing:

- Video are rendered black
- Missing shadows
- Missing volumetric effects
- Color grading
- Missing image blur

With 0.13:

- Everything expect of cut scenes and menus is rendered black

Blur:
![vlcsnap-2019-06-09-14h35m33s847](https://user-images.githubusercontent.com/11244092/59159070-ba941200-8ac4-11e9-80c2-91938bd000d8.png)
![vlcsnap-2019-06-09-14h35m52s358](https://user-images.githubusercontent.com/11244092/59159073-bff15c80-8ac4-11e9-9ec3-56e0e3c9c8c2.png)

Shadows:
![vlcsnap-2019-06-09-14h37m14s686](https://user-images.githubusercontent.com/11244092/59159079-cbdd1e80-8ac4-11e9-893c-f6fc36fc3a3e.png)
![vlcsnap-2019-06-09-14h37m23s871](https://user-images.githubusercontent.com/11244092/59159082-d39cc300-8ac4-11e9-90fc-571a9c7a90a8.png)

Volumetric effects or probably just pales with translucent textures.
![vlcsnap-2019-06-09-14h38m01s675](https://user-images.githubusercontent.com/11244092/59159092-efa06480-8ac4-11e9-8a46-bdae54fb9cd0.png)
![vlcsnap-2019-06-09-14h37m58s211](https://user-images.githubusercontent.com/11244092/59159094-f4651880-8ac4-11e9-8e15-4e700d3f891d.png)

### Software information
HITMAN Blood Money
- Settings: Max

### System information
- GPU: GeForce GTX 1080
- Driver: 430.14
- Wine version: Proton 4.2-6
- DXVK version: 0.12

### Apitrace file(s)
- https://drive.google.com/open?id=15q35w2OaKsTtPFEWxWQ9rBhZ3ItuNDM2

**Comment by qdevpl** [comment] 2019-07-09 19:55
Were those effects missing for you when set to Max? When I set Post processing effects LOD to something other than "none" I'm getting black render. 
![20190709214006_1](https://user-images.githubusercontent.com/10712189/60918666-31732500-a294-11e9-80af-89627adc2f20.jpg)

With 0.13 in game movies are working now.

**Comment by VortexAcherontic** [comment] 2019-07-10 16:06
@qdevpl I can confirm that with d9vk 0.13 everything (except of text and cut scenes) renders black. The screenshots above where made with d9vk 0.12

**Comment by CME42** [comment] 2019-07-14 15:38
This is fixed in the latest master, can you guys please try it?

**Comment by qdevpl** [comment] 2019-07-15 18:28
To me it work spot on! Performance is way more stable than d3d, it locks at monitor framerate and stays that way.

![20190715202301_1](https://user-images.githubusercontent.com/10712189/61239284-d67f7900-a73e-11e9-9fb9-d82222950e49.jpg)
![20190715202332_1](https://user-images.githubusercontent.com/10712189/61239290-d8e1d300-a73e-11e9-8cfc-f77e0d3a8784.jpg)
![20190715202340_1](https://user-images.githubusercontent.com/10712189/61239295-daab9680-a73e-11e9-8b31-3dd8cb95c00a.jpg)
![20190715202358_1](https://user-images.githubusercontent.com/10712189/61239298-dc755a00-a73e-11e9-8a72-4dce0a51d4b4.jpg)
![20190715202432_1](https://user-images.githubusercontent.com/10712189/61239303-de3f1d80-a73e-11e9-8b04-a06ddc6d6ac8.jpg)
![20190715202517_1](https://user-images.githubusercontent.com/10712189/61239310-e0a17780-a73e-11e9-8a6d-d2777569675a.jpg)

**Comment by VortexAcherontic** [comment] 2019-07-15 21:15
I also can confirm that it looks absolutely beautiful :+1: 

Feel free to close this issue I feel like everything is working as it should :D

**Closed** 2019-07-16 19:17 UTC

**Comment by NerosTie** [comment] 2019-07-17 19:19
With the latest master, it's flickering a lot, even in the first menu.

**Comment by Joshua-Ashton** [comment] 2019-07-17 19:22
Is this a new regression @NerosTie? Can you bisect?

**Comment by NerosTie** [comment] 2019-07-17 19:43
Yes, it's a regression. I have the same issue with Skydrift (yes, this game again).
I think it's latest commit, #635 in the pipelines, because it works with #633.
