### ISSUE TITLE
The Witcher not rendering correctly

### ISSUE THREAD

**Issue by AccountOneOff** [Joshua-Ashton/d9vk#15] opened 2019-04-12 04:51 UTC
The Witcher doesn't render intro movies (green screen) but it does render the menu screen just not the menus. I can load my game save but it crashes before ever reaching in-game.

![Screenshot from 2019-04-11 21-15-23](https://user-images.githubusercontent.com/15083452/56012554-d6845e80-5ca1-11e9-9566-c273243ef92f.png)

![Screenshot from 2019-04-11 21-15-25](https://user-images.githubusercontent.com/15083452/56012519-b9e82680-5ca1-11e9-8cb0-ae009690b5cc.png)

### Software information
The Witcher Enhanced Edition w/ Rise of the White Wolf mod

### System information
- GPU: GTX 960
- Driver: 418.56
- Wine version: Staging 3.21
- DXVK version: b71f5148797fba8e2a78fdb265020216cebb725d

### Apitrace file(s)
- https://drive.google.com/open?id=1Ovokqp7miqC02vq7eM8rXZNZTHQGIGry

### Log files
- [witcher_d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3071586/witcher_d3d9.zip)

**Comment by Valmar33** [comment] 2019-04-12 07:06
Fixing this requires Joshua to implement all of those unhandled render state warnings, along with some of the stubs, so maybe there's not much point in submitting bug reports just yet. D9VK needs a lot more functionality implemented.

It's a hit and miss if you game will run with glitches, or just crash.

**Comment by Joshua-Ashton** [comment] 2019-04-12 10:21
> Fixing this requires Joshua to implement all of those unhandled render state warnings, along with some of the stubs

It probably doesn't

**Comment by Valmar33** [comment] 2019-04-12 14:34
Probably, I hope. :)

**Comment by Valmar33** [comment] 2019-04-12 17:37
Hopefully not. :)

**Comment by AccountOneOff** [comment] 2019-04-12 23:19
>so maybe there's not much point in submitting bug reports just yet.

Everyone's posting their games on Discord already. Don't see why posting it here would be a problem. @Joshua-Ashton should I move my open issues from dxup to this repo or would that be too annoying? Don't know if you forgot about all those traces I have.

**Comment by Valmar33** [comment] 2019-04-13 07:47
Huh, didn't know that.

Do you know what the Discord channel is?

**Comment by AccountOneOff** [comment] 2019-04-20 22:59
Intro videos now render and I'm able to get in-game. 

Menus regressed though:
![Screenshot from 2019-04-20 15-54-05](https://user-images.githubusercontent.com/15083452/56463230-cac12800-6384-11e9-9e3b-7f0cc462df4e.png)

In-game:
![Screenshot from 2019-04-20 15-52-49](https://user-images.githubusercontent.com/15083452/56463231-d4e32680-6384-11e9-92d6-0da04877cfc6.png)

Inventory:
![Screenshot from 2019-04-20 15-53-41](https://user-images.githubusercontent.com/15083452/56463233-df052500-6384-11e9-981a-878572fea750.png)


[d3d9_log.zip (322MB decompressed)](https://github.com/Joshua-Ashton/d9vk/files/3100677/d3d9_log.zip)

**Comment by K0bin** [comment] 2019-04-21 00:20
Please bisect to find out which commit made it regress.

**Comment by AccountOneOff** [comment] 2019-04-21 04:01
Trying to but getting this:

```
cxf@PC:~/d9vk$ git bisect bad
You need to start by "git bisect start"
Do you want me to do it for you [Y/n]?
cxf@PC:~/d9vk$ git bisect good b71f514
fatal: Needed a single revision
Bad rev input: b71f514
```

**Comment by neVERberleRfellerER** [comment] 2019-05-07 22:31
Is this good? (ignore the FPS, it's caused by log spam)
![Screenshot_20190508_002903 png](https://user-images.githubusercontent.com/11160972/57337145-98efe580-7128-11e9-97ea-4806d90dcfec.jpg)

**Comment by Venemo** [comment] 2019-05-11 10:24
This is what I get:

![Screenshot from 2019-05-11 12-09-43](https://user-images.githubusercontent.com/722813/57568434-c0c0a100-73e7-11e9-90b2-88599064d705.png)

**Comment by axredneck** [comment] 2019-07-17 13:52
Currently Witcher 1 works for me but with some glitches:
![2019-07-17-155014_1920x1080_scrot](https://user-images.githubusercontent.com/20617900/61381090-30a14b00-a8b3-11e9-87ba-5005aeefabf5.jpg)
[witcher_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3402179/witcher_d3d9.log)

**Comment by axredneck** [comment] 2019-07-24 22:18
Updated log, it's a bit different with current d9vk master:
[witcher_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3428930/witcher_d3d9.log)
But glitches are the same.

**Comment by Joshua-Ashton** [comment] 2019-07-24 22:32
Yeah it's out of bounds constant access

**Comment by shmerl** [comment] 2019-08-02 04:00
Works fine for me now btw, except for one issue (blinking when forcing vsync). By default the game doesn't have vsync option, so it renders at almost 150 fps for me on my 60Hz monitor.

But when I force it like this:

```
MESA_VK_WSI_PRESENT_MODE=fifo
```
It starts rendering with 60 fps like expected, but it also produces periodic black blinking. Is it d9vk or radv issue?

Though I'm running it with a bit older Mesa (19.1.2/llvm 8.0.1), due to mess of building 32-bit one.

**Comment by Joshua-Ashton** [comment] 2019-08-02 04:28
Or use d3d9.presentInterval = 1

**Comment by shmerl** [comment] 2019-08-02 04:31
```
d3d9.presentInterval = 1
```
That's in d9vk config file?

**Comment by Joshua-Ashton** [comment] 2019-08-02 04:31
dxvk.conf

**Comment by shmerl** [comment] 2019-08-02 04:37
OK, that option works, but produces the same problem - periodic blinking. I suppose it does the same thing, just forcing fifo mode. Do you think it's a radv bug?

**Comment by axredneck** [comment] 2019-08-02 14:29
For me glitches are still here.
D9VK-master, Wine 4.12.1, Arch Linux, Nvidia driver 430.40, with and without winetricks d3dx9* and d3dcompiler*

**Comment by shmerl** [comment] 2019-08-02 15:48
@axredneck : Does adding that setting in the registry I mentioned above help?

**Comment by K0bin** [comment] 2019-08-02 16:19
That registry setting only impacts WineD3D. We need to implement something similar for D9VK but haven't done so yet. After that's implemented it will probably be turned on by default.

**Comment by shmerl** [comment] 2019-08-02 16:21
Then somehow this issue is not affecting AMD / radv.

**Comment by Joshua-Ashton** [comment] 2019-08-02 22:27
Yes because OOB access is UB and works fine on AMD but returns garbage on NV.

**Comment by shmerl** [comment] 2019-08-14 02:52
@Joshua-Ashton: so do you think the flickering with vsync enabled is d9vk related (and same problem like above), or it's something with radv and I should report it to Mesa?

**Comment by tannisroot** [comment] 2019-08-14 11:40
> periodic blinking
what do you mean by "blinking" exactly?

**Comment by shmerl** [comment] 2019-08-26 05:11
@tannisroot: the scene periodically turns dark (or black - it's hard to see), for a very short moment, which happens once in a while. It only occurs when vsync is on like I said above.

**Comment by Joshua-Ashton** [comment] 2019-09-07 19:23
May be fixed now.

**Comment by NerosTie** [comment] 2019-09-07 20:26
The game is not glitching anymore.

Everything looks fine now, maybe this issue can be closed.

**Closed** 2019-09-07 21:27 UTC

**Comment by axredneck** [comment] 2019-09-07 23:25
Thank You, Joshua!

**Comment by Joshua-Ashton** [comment] 2019-09-08 01:11
It was @doitsujin who did the fix 🐸
