### ISSUE TITLE
Alan Wake crashes on launch

### ISSUE THREAD

**Issue by LeJimster** [Joshua-Ashton/d9vk#64] opened 2019-05-02 12:55 UTC
It opens to a black screen for a second then crashes out.

### Software information
Alan Wake (Steam)

### System information
- GPU: RX Vega 56
- Driver: Mesa 19.1-git (git-07745f9494)
- Wine version: Proton 4.2-3
- DXVK version: 98a24c89

### Apitrace file(s)
- https://drive.google.com/open?id=1ET6N1c4Cn6L9lXjbOY9mUhfJauTY6Q4G

### Log files
- d3d9.log: [AlanWake_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3138083/AlanWake_d3d9.log)

**Comment by loathingKernel** [comment] 2019-05-07 09:48
It also happens on vanilla wine 4.7, wine-staging 4.7 and Windows too.

**Comment by neVERberleRfellerER** [comment] 2019-05-10 13:59
For me with RADV 19.0.3 d3dretrace crashes in this after playing "REMEDY" logo video.
https://github.com/mesa3d/mesa/blob/mesa-19.0.4/src/amd/vulkan/radv_meta.c#L230 .
```
Backtrace:
=>0 0xf765f1b6 radv_builtin_cache_path.part+0x52596() in libvulkan_radeon.so (0xef549a70)
  1 0xf76576e6 radv_builtin_cache_path.part+0x4aac5() in libvulkan_radeon.so (0xf789b764)
  2 0xf765b1c5 radv_builtin_cache_path.part+0x4e5a4() in libvulkan_radeon.so (0x00000007)
  3 0xf765d193 radv_builtin_cache_path.part+0x50572() in libvulkan_radeon.so (0x7cb4a450)
  4 0xf765d276 radv_builtin_cache_path.part+0x50655() in libvulkan_radeon.so (0x01f2f2a8)
  5 0xf7a57a90 wine_vkCreateGraphicsPipelines+0x1af() in winevulkan (0x01f2f208)
  6 0x624993b1 in d3d9 (+0x593b0) (0x01f2fcb8)
  7 0x6249a3d8 in d3d9 (+0x5a3d7) (0x01f2fd68)
0xf765f1b6 radv_builtin_cache_path.part+0x52596 in libvulkan_radeon.so: movl    0xc(%eax),%ebx
```

**Comment by loathingKernel** [comment] 2019-05-11 07:22
> UPDATE 2: It is stack corruption. Whan I change the paths and prefixes slightly, I get much further - past the menu:

Can you describe what you mean by slightly? What change affected it?

**Comment by neVERberleRfellerER** [comment] 2019-05-11 07:45
> Can you describe what you mean by slightly please?
I have replaced paths used by RADV with single 2 letter ones and other crap, but it's useless with nv and game crashes anyway, just slightly later. Actually, it's a miracle that there are differences in runtime. It could also be bug in RADV that just causes crash at the same place you get with nv.
> What change affected it?
No idea.

**Comment by loathingKernel** [comment] 2019-05-11 17:13
Somewhere in the last 12 commits it started working for me on Nvidia. Not sure which one did it though.

**Comment by neVERberleRfellerER** [comment] 2019-05-11 17:15
I have just finished tests on AMDVLK - it works, so only RADV 19.0.3 is problematic. Well, it was interesting. Too bad I didn't know that it's fixed on nvidia. I hope I didn't bother anybody with update spam.
![Screenshot_20190511_191159 png](https://user-images.githubusercontent.com/11160972/57572886-ffbf1880-7420-11e9-9da1-9fdabf1352fd.jpg)

**Comment by loathingKernel** [comment] 2019-05-11 17:23
> I hope I didn't bother anybody with update spam.
I think you did an awesome job trying to find the cause. I just did my daily rebuild of d9vk and found out it started working.

**Comment by LeJimster** [comment] 2019-05-11 22:43
> I have just finished tests on AMDVLK - it works, so only RADV 19.0.3 is problematic. Well, it was interesting. Too bad I didn't know that it's fixed on nvidia. I hope I didn't bother anybody with update spam.
Nope, we all appreciate the effort if it uncovers a driver bug.  So do we need to open a bug report for radv, or is there a workaround that can be done with d9vk?  I'm not really interested in switching to AMDVLK just yet, for the most part that driver isn't as good/stable as RADV yet.

**Comment by LeJimster** [comment] 2019-05-12 01:45
I found that I had a copy of an older d3d9.dll (d9vk build) in Alan Wakes /data directory that shouldn't have been there.  After deleting that, the game works with the most recent build  ca3c81c1 with RADV.

Can anyone else confirm it now works with RADV?  I noticed this video which seems to indicate I'm not the only one. https://www.youtube.com/watch?v=mBN-J4lyj2A

**Comment by neVERberleRfellerER** [comment] 2019-05-12 09:36
Confirming with d3dretrace:
![Screenshot_20190512_113237 png](https://user-images.githubusercontent.com/11160972/57580439-e0b89900-74a9-11e9-9a29-7d7285a786bc.jpg)
I have also learned, that it's possible to use LD_LIBRARY_PATH with libLLVM and modified ICD JSON to load RADV from git without having to change global mesa, because RADV does not link to anything from mesa.

**Closed** 2019-05-12 12:16 UTC
