### ISSUE TITLE
Fallout: New Vegas intro movie has black screen and launcher has minor issue

### ISSUE THREAD

**Issue by CartoonFan** [Joshua-Ashton/d9vk#163] opened 2019-06-10 08:11 UTC
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Fallout: New Vegas

### System information
- GPU: Nvidia GeForce GTX 960
- Driver: 430.14.0
- Wine version: 4.9 TKG
- DXVK version: https://github.com/Joshua-Ashton/d9vk/commit/d8b9b5fedf081a40f00d5c20d49099a6ead6ecdf

### Apitrace file(s)
Game:
https://drive.google.com/file/d/1mMcUaZg9u-ZvDJRZ6TXj09JRhj-HVuKd/view?usp=sharing
https://drive.google.com/file/d/1Rp_GtbIOCeeqJrfEjNWWbTkW5ULL-vMa/view?usp=sharing

Launcher:
https://drive.google.com/file/d/1S0dHl9RD6307wAbrTmCHdzS-OulKcSKY/view?usp=sharing
https://drive.google.com/file/d/1DIQ7yjtxoSkt27dmHv3YiWS-NOG3ZQsu/view?usp=sharing

### Log files
Game:
- d3d9.log:
[FalloutNV_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3271133/FalloutNV_d3d9.log)

Launcher:
- d3d9.log:
[FalloutNVLauncher_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3271155/FalloutNVLauncher_d3d9.log)

The intro movie after starting a new game is completely black. Also, it's probably really minor, but the launcher automatically sets the graphics to Ultra High quality under wined3d, but sets them to High with D9VK.

**Comment by Joshua-Ashton** [comment] 2019-06-11 11:02
Duplicate of #60

**Comment by Joshua-Ashton** [comment] 2019-06-11 11:02
Regarding "but the launcher automatically sets the graphics to Ultra High quality under wined3d, but sets them to High with D9VK," probably a minor caps difference.

**Closed by Joshua-Ashton** 2019-06-11 11:02 UTC
