### ISSUE TITLE
Guild wars 2 cursor remains on screen and blocks turning camera

### ISSUE THREAD

**Issue by Mel34** [Joshua-Ashton/d9vk#66] opened 2019-05-04 19:12 UTC
Guild wars 2 uses right click to start turning the camera. Typically cursor disappears and you are free to rotate the camera as many degrees as you want. If d9vk is used, cursor remains on  screen and rotation is limited by cursor hitting the screen left or right edges. Game also has action camera mode in which cursor also disappears, again not the case when d9vk is used. Cursor remains on screen and limits the turning by bumping into screen edge and staying there. Is this the relative cursor/absolute cursor issue? I didn't provide any logs because this isn't a crash. I'll be happy to provide them for you should you need them.

Sometimes the bug only manifests when a map change happens (works on the initial map, breaks when you change zones)

### Software information
Running Guild Wars 2 64 bit on Archlinux

### System information
- GPU: AMD Rx580
- Driver: vulkan-radeon 19.0.3-1
- Wine version: 4.7-1 or 3.18-esync-pba or 4.6-tkg
- DXVK version:  git master 6f9a3e6e

**Comment by Joshua-Ashton** [comment] 2019-05-04 19:13
Log would be helpful here

**Comment by Mel34** [comment] 2019-05-04 19:19
[Gw2-64_d3d9.log](https://send.firefox.com/download/c3cb691d66dccc70/#vqrn8qHC_ZJHsELX69XzCw)
Gw2-64_dxgi.log and Gw2-64_d3d11.log are empty

**Comment by yaomtc** [comment] 2019-05-04 19:20
I had this issue with Wine if I had "emulate a virtual desktop" enabled. Do you have this option enabled? If so, try enabling "Automatically capture mouse in full-screen windows".

**Comment by Mel34** [comment] 2019-05-04 19:24
@yaomtc I don't have virtual desktop enabled. Enabling AUtomatically capture mouse didn't help either.

**Comment by Mel34** [comment] 2019-05-04 19:37
btw @Joshua-Ashton 6f9a3e6 causes text corruption in GW2. [Check it out here](https://imgur.com/653kpXR). 
a63208b1 seems fine.

**Comment by Joshua-Ashton** [comment] 2019-05-04 19:43
> 
> 
> btw @Joshua-Ashton [6f9a3e6](https://github.com/Joshua-Ashton/d9vk/commit/6f9a3e6e6f1e721908b5154d41094f75a05ff9d9) causes text corruption in GW2. [Check it out here](https://imgur.com/653kpXR).
> [a63208b](https://github.com/Joshua-Ashton/d9vk/commit/a63208b17d74285e0b18856c4c3a041d1d14162c) seems fine.

Can you see if 1626606cee8af5f1dc17e203e0458bf333b7fee6 corrects that issue?

**Comment by Mel34** [comment] 2019-05-04 19:45
Sure, just waiting for froggi.es to build it.

**Comment by Mel34** [comment] 2019-05-04 20:03
No luck. [Result](https://imgur.com/7ZYAqI5)

**Comment by logan001** [comment] 2019-05-04 20:11
for me on 0c3c570 it happens like this
on 1st character that i start to play the mouse behave as it should - disapear when drag with left or right click
if i select another character the mouse will stay on when drag it around. but i have no issue with being unable to rotate the camera. even if the mouse hits the edge of the screen, i'll still be able to rotate th camera. only "glitch" is that after releasing the button (stop rotate) the mouse will move back to initial position where it was before rotating camera.
text looks good on that window for me

**Comment by Joshua-Ashton** [comment] 2019-05-04 20:19
> 
> 
> No luck. [Result](https://imgur.com/7ZYAqI5)

I mean, it doesnt look like garbage anymore -- that's a start. Lemme take another look into it

**Comment by Mel34** [comment] 2019-05-04 20:23
@logan001 mouse moving back shouldn't be a glitch, glitch is mouse cursor not disappearing in the first place. Have you tried loading another map? This manifests for me when I change map (e.g. go into fractals lobby)

**Comment by logan001** [comment] 2019-05-04 20:34
yes, after changing maps the mouse does not disappear anymore. except on one occasion when the mouse had no issue
but i can still rotate camera without any other problems.

**Comment by Joshua-Ashton** [comment] 2019-05-04 20:38
> 
> 
> @logan001 mouse moving back shouldn't be a glitch, glitch is mouse cursor not disappearing in the first place. Have you tried loading another map? This manifests for me when I change map (e.g. go into fractals lobby)

Can you see if this dll rectifies the issue?
[d3d9.zip](https://github.com/Joshua-Ashton/d9vk/files/3144811/d3d9.zip)

**Comment by Mel34** [comment] 2019-05-04 20:48
> d3d9.zip

Sadly, no. I tried it and mouse stays on screen.

**Comment by Joshua-Ashton** [comment] 2019-05-04 20:48
its not meant to be for the mouse, its meant to be for the text

**Comment by Mel34** [comment] 2019-05-04 20:52
Just tried it with 1626606c + that dll replacement. It works! See [here](https://imgur.com/KAe8YO1)

**Comment by logan001** [comment] 2019-05-04 20:53
@Joshua-Ashton it doens't fix it.
the mouse still stays on the screen after changing maps.

**Comment by Joshua-Ashton** [comment] 2019-05-04 20:54
> its not meant to be for the mouse, its meant to be for the text

**Comment by Mel34** [comment] 2019-05-04 20:56
I should've filed another bug report for the text :laughing:

**Comment by logan001** [comment] 2019-05-04 21:03
also 1626606c does not fix the text issue.
the behavior is random.
on some tries the 1st panel had right side with no text plus the text below was missing (even on buttons)
on 2nd try the text as rendered as vertical lines.
on 3rd try was like this
![gw001](https://user-images.githubusercontent.com/6472378/57184776-2208e180-6ec9-11e9-9839-514cd12ea54a.jpg)

**Comment by Mel34** [comment] 2019-05-04 21:05
Yeah it doesn't fix it on it's own, you're supposed to combine it with the d3d9.zip posted in https://github.com/Joshua-Ashton/d9vk/issues/66#issuecomment-489363720

**Comment by logan001** [comment] 2019-05-04 21:10
@Joshua-Ashton yes text seems to be ok

**Comment by Mel34** [comment] 2019-05-04 21:12
a026a422 fixes text issue.

**Comment by marcelomendes** [comment] 2019-05-05 05:09
> for me on [0c3c570](https://github.com/Joshua-Ashton/d9vk/commit/0c3c570343792f0aa471532dac2424915f71ff2f) it happens like this
> on 1st character that i start to play the mouse behave as it should - disapear when drag with left or right click
> if i select another character the mouse will stay on when drag it around. but i have no issue with being unable to rotate the camera. even if the mouse hits the edge of the screen, i'll still be able to rotate th camera. only "glitch" is that after releasing the button (stop rotate) the mouse will move back to initial position where it was before rotating camera.
> text looks good on that window for me
I can confirm this exact same behavior, first character works as it should, but if you change it the mouse cursor won't go away.

**Comment by Jrugia** [comment] 2019-05-05 10:48
Rotating the camera for me doesn't block at the screen's edge for me either. the cursor issue is present as everyone else.

**Comment by garpu** [comment] 2019-05-07 15:14
Just tried it with the most recent build (https://git.froggi.es/joshua/d9vk/commit/01b0a3be60cb728c3feaaca215241f1bae304551).  The cursor issue appears to be fixed.

**Comment by Mel34** [comment] 2019-05-07 15:24
@garpu have you tried changing maps?

**Comment by garpu** [comment] 2019-05-07 15:30
I take that back.  It was fine when I loaded a map, then when I zoned elsewhere, it's back. :/

**Comment by TheDaftRick** [comment] 2019-05-08 19:38
**Issue:**
Mouse cursor remains on screen when it should be hidden.
Normally holding left or right click or going into Action Camera will hide the mouse cursor when rotating the camera.

Issue only happens after a loading screen after initially loading in the game.

Issue does not happen if you have the mouse cursor hidden when initializing the loading screen (ex: If you have action camera enabled which hides the mouse cursor or if you hold down the left or right click and you walk through a portal)

**Attempted fixes:**
- Windowed mode
- Full screen windowed
- Full screen 
- All settings to highest
- All settings to lowest

**System:**
- Ubuntu 19.04 (Gnome 3.32.1)
- Intel i5-4460
- Nvidia GT-1030 (driver 430.09)
- Wine tkg-4.6-x86_64
- d9vk 0.10

[GW2-64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3158961/GW2-64_d3d9.log)

**Comment by Mel34** [comment] 2019-05-10 17:56
> Issue does not happen if you have the mouse cursor hidden when initializing the loading screen

Good catch. If the bug triggers even once then this trick doesn't help anymore.

**Comment by Mel34** [comment] 2019-05-12 10:11
Update: camera turning blocking in my case is caused by sway (the wayland window manager). It constrains the cursor to a screen with the game. Running the game under kwin leads to cursor remaining on screen during camera turning, allowing more than one rotation around the character axis and it does warp back to where it was when the drag option was initiated.

**Comment by l33afpad** [comment] 2019-05-12 16:14
> Update: camera turning blocking in my case is caused by sway (the wayland window manager). It constrains the cursor to a screen with the game. Running the game under kwin leads to cursor remaining on screen during camera turning, allowing more than one rotation around the character axis and it does warp back to where it was when the drag option was initiated.

I have the same problem with the xfce4 window manager

**Comment by Mel34** [comment] 2019-05-12 16:56
@logan001 which window manager/compositor are you using?

**Comment by DxCx** [comment] 2019-05-12 20:03
im not sure which window manager is the default but i have xfce4 (xf4wm) as main desktop,
openbox as desktop for gaming.
and im having the same issue with cursor displaying..
any more info i can provide to debug this?

**Comment by Mel34** [comment] 2019-05-12 21:15
Logs would probably help.

**Comment by TheDaftRick** [comment] 2019-05-13 03:01
Still an issue with d9vk 0.11
Not sure if it matters, but it viewing a vista also triggers the bug.

**Comment by DxCx** [comment] 2019-05-13 04:46
Logs? D9vk logs? (DXVK_LOG_LEVEL=debug?)
Or api trace which ive seen here around but no instructions how to dump myself..

**Comment by Mel34** [comment] 2019-05-13 07:01
> DXVK_LOG_LEVEL=debug
Yeah, unless @Joshua-Ashton wants api traces as well?

**Comment by DxCx** [comment] 2019-05-13 08:21
There you go:
Using v0.11 tag (at least that's what i've installed (https://git.froggi.es/joshua/d9vk/-/jobs/441/artifacts/download), log says 0.10 for some reason),
GeForce GTX 1050 Mobile (Driver version 418.56)

[GW2-64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3171839/GW2-64_d3d9.log)

P.S
this is with ArcDps enabled (loaded to memory at least), however, ArcDps ui is not showing up,
i did note i didnt remove this try of making arcdps work before capturing the log, maybe the log can reveal why its not showing up but i hope its not "trashing" it.
anyway, if clean log recapture is needed let me know i'll redo it

**Comment by DxCx** [comment] 2019-05-16 08:35
Ok,
so i've retested without ArcDps and with latest master (8930577d - https://git.froggi.es/joshua/d9vk/-/jobs/452/artifacts/download)

cursor bug still exists..
here are updated log:
[GW2-64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3186100/GW2-64_d3d9.log)

**Comment by Mel34** [comment] 2019-05-16 10:09
I'm tracking @Joshua-Ashton's commits every day and testing every build. He's making huge progress and hopefully his work enables d9vk on more games. A cursor glitch in one game isn't really a priority when there are so many reports about games not working or crashing.
That being said, that cursor glitch is the only thing that's missing from 100% perfect experience of playing GW2 under d9vk. Let's hope he finds some time to look into the cursor code soon.

**Comment by DxCx** [comment] 2019-05-16 12:41
well, i have alot of technical knowledge/experience, not in 3d or gaming, but in programing in general.
if i get some hints on stuff worth checking / debugging i would really like to help.
especially since this is the ONLY game i play hehe

**Comment by Mel34** [comment] 2019-05-16 23:15
Just tried KDE 5.15.90 (5.16 beta) wayland session. Mouse blocking issue is present with kwin_wayland as compositor as well.

**Comment by DxCx** [comment] 2019-05-17 13:28
Ok since i really want to make GW2 works good with d9vk i started to read abit around and get into how d9 and graphic works. (still very young tough XD).

anyway, as first step i've dumped an API trace file that should reproduce the problem:
1. Log-in into charcter
2. Change map
3. Rotate camera

Next using `WINEPREFIX=~/lutris_Games/guild-wars-2/ wine ./apitrace/bin/apitrace.exe replay gw2.trace `
i am able to see the trace i've created.
Next i assume i'll need to replay it using d9vk dlls just not sure how to do that just yet..

anyway i am uploading the trace into my drive (400MB)
and i'll post a link in here

**Comment by Mel34** [comment] 2019-05-17 18:02
@DxCx When opening an issue here, this is printed out in the template:

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

**Comment by DxCx** [comment] 2019-05-17 20:03
Exactly what i did, this is raw apitrace with no DXVK
I had to call it a day, so ill continue only tommorow
But i thought about it and i think that next i should be able to replay with DXVK loaded and attach a debugger

**Comment by Jrugia** [comment] 2019-05-17 21:10
From my experience with D9VK so far, this isn't just a GW2 issue, I've encountered the issue with a few other games too, and some issue reports mention it too. Fixing this will probably fix other games too.

**Comment by Mel34** [comment] 2019-05-17 21:16
@Jrugia can you list those other games?

**Comment by DxCx** [comment] 2019-05-17 21:17
If @Joshua-Ashton or anyone else who is more familiar with d9vk can throw me some hints i would be glad to help fix it out.

**Comment by AlexeyProkhin** [comment] 2019-05-18 05:59
@DxCx try to apply [this patch](https://github.com/ValveSoftware/wine/commit/200ab34e5bd329f773c362e23a556a9a6a3fc516#diff-adc23fa7bcadeff404bb73143ff1699f) to wine. Basically, there is a check in wine to rate limit applying   fullscreen mouse clipping. This patch partially removes the check.
You could also try to modify d9vk/dxvk to call ChangeDisplaySettingsExW() less. WineD3D checks if the resolution is actually changed before calling the function. See [this line](https://github.com/ValveSoftware/wine/blob/c89465427eb5b3a7ef9ef312517083950ea5959e/dlls/wined3d/directx.c#L1135) for inspiration.

**Comment by DxCx** [comment] 2019-05-18 06:29
Awsome! Thanks for the tips @AlexeyProkhin :)
Will try it soon and update back what ive learned

**Comment by DxCx** [comment] 2019-05-18 06:46
I dont have a windows system myself so i cant confirm it,
Is this bug happens on windows too?

I mean, wine rate limit makes sense to blame, but if it is the culprit then the bug shouldnt happen on windows

**Comment by logan001** [comment] 2019-05-18 09:30
> 
> 
> @logan001 which window manager/compositor are you using?

sorry for late response. just for info i've tried both Cinnamon and KDE and both allow me to rotate the camera even thought the mouse will stay at the edge of the screen.

**Comment by logan001** [comment] 2019-05-18 09:55
> 
> 
> I dont have a windows system myself so i cant confirm it,
> Is this bug happens on windows too?
> 
> I mean, wine rate limit makes sense to blame, but if it is the culprit then the bug shouldnt happen on windows

this "bug" does not happen in windows.

i think this bug use to be present a long time ago in wine (before x64 version of GW). but i'm not sure if its the same bug as we have now.
Here is something related to cursor problem on [winehq](https://bugs.winehq.org/show_bug.cgi?id=31702)
maybe its the same issue. maybe not. i have no clue. but maybe someone can figure it out.

**Comment by Jrugia** [comment] 2019-05-18 14:44
> @Jrugia can you list those other games?

Aside from GW2 there are:

Crysis
GTA IV
Colin McRae Dirt

**Comment by DxCx** [comment] 2019-05-19 11:11
Ok so thanks @AlexeyProkhin.

I've never compiled wine before so it took me abit to get it working, but i was able to clone and compile wine-tkg 4.6 (and make sure game works the same before the patch)

after that, i've ported the patch and placed it with `.mypatch` extention under `wine-tkg-userpatches` folder.
patch file can be found here: [wine4.6-winex11-ignore-clip_reset-when-trying-to-clip-the-mo.txt](https://github.com/Joshua-Ashton/d9vk/files/3194958/wine4.6-winex11-ignore-clip_reset-when-trying-to-clip-the-mo.txt) (Don't forget to rename to .mypatch extention if you try to reproduce)

However, after applying the patch the problem still exists.
i'll try to think how to tackle this better, but having the ability to compile and run my own wine is already a step forward i believe =)

**Comment by AlexeyProkhin** [comment] 2019-05-19 11:37
@DxCx Sorry to hear the patch did not help. You could also try to apply [another proton patch](https://github.com/ValveSoftware/wine/pull/28/commits/c414ab242abaf381e1e707daec6ff83a7ec84892) as well.

**Comment by DxCx** [comment] 2019-05-19 17:12
@AlexeyProkhin ive added this patch as well, nope, still doesnt work..
Do you maybe know any wine debug prints worth enabling for understanding this better?

**Comment by AlexeyProkhin** [comment] 2019-05-19 17:38
@DxCx cursor and x11drv probably. But it does not seem to be an issue I had in mind. So maybe it is in totally different place. I don't know the wine (and d9vk) codebase well enough to make another guess.

**Comment by logan001** [comment] 2019-05-19 17:55
@AlexeyProkhin do you have amd card?

**Comment by AlexeyProkhin** [comment] 2019-05-19 18:07
@logan001 , no. Why do you ask?

**Comment by logan001** [comment] 2019-05-19 18:20
i was curios if it that fix it for you then maybe its a problem of drivers.

**Comment by Mel34** [comment] 2019-05-19 21:52
Just FYI: Playing the new map without d9vk caused OOM killer to kill gw2 twice tonight, it's leaking memory it seems (filled my 16gb and I have no swap). Under d9vk it doesn't leak and overall seems memory usage is lower.

**Comment by Joshua-Ashton** [comment] 2019-05-20 02:12
Is this fixed in latest master?

**Comment by yaomtc** [comment] 2019-05-20 03:00
It is now fixed for me. Thanks, @Joshua-Ashton!

**Comment by sypher7** [comment] 2019-05-20 03:07
It is also fixed for me in master, thank you @Joshua-Ashton!

**Comment by DxCx** [comment] 2019-05-20 05:08
Awsome news @Joshua-Ashton 
https://git.froggi.es/joshua/d9vk/commit/35a9423648153ecb08e195e5f0c400aa4f4ddc97
fixes this issue.
THANKS ALOT!

**Comment by Joshua-Ashton** [comment] 2019-05-20 07:13
cool

**Closed by Joshua-Ashton** 2019-05-20 07:13 UTC

**Comment by Mel34** [comment] 2019-05-20 09:33
Oh my God it works. Thank you so much! ❤️
