### ISSUE TITLE
Tomb Rader 'Legends' trilogy has serious mouse lag when using D9VK

### ISSUE THREAD

**Issue by FurtiveDolus** [Joshua-Ashton/d9vk#440] opened 2019-10-30 20:59 UTC
Pretty much what it says in the title. The mouse lags terribly on my older FX 8350 box. It's still there but less noticeable on my newer Ryzen 2700X PC. What I notice in the HUD is that the CPU usage spikes hard every time you move the mouse. Doesn't happen with a controller, doesn't happen with OpenGL.

OSes: Fedora 30 & 31
CPU: FX 8350 & Ryzen 2700x
GPU: RX 480 & Vega 56
RAM: 16 gigs of DDR3 & 32 gigs of DDR4

**Comment by K0bin** [comment] 2019-10-30 21:01
Please make an apitrace.

**Comment by FurtiveDolus** [comment] 2019-10-30 22:47
Same procedure for Steam games as the one in your wiki?

**Comment by K0bin** [comment] 2019-10-30 22:54
Yes

**Comment by K0bin** [comment] 2019-11-03 15:39
The game for some reason defaults to 24hz for me. Make sure to check if the refresh rate is set correctly in the menu.

**Comment by FurtiveDolus** [comment] 2019-11-03 18:58
Sorry for the delay. As it happens the RX 480 in my older box died on me.
I'll test this on the newer box with the Ryzen and Vega hardware when I get
off work.

**Comment by FurtiveDolus** [comment] 2019-11-04 05:36
Apologies. This issue isn't noticeable on the newer hardware and the traces I made were far too small to have been successful.

**Comment by Joshua-Ashton** [comment] 2019-11-04 05:37
Are we sure this isn't just some stupid mouse polling bug?

**Comment by FurtiveDolus** [comment] 2019-11-04 05:39
Wouldn't it happen with the same mouse even on different machines? Both were running on Fedora 31. So only the HW differed.

**Comment by Joshua-Ashton** [comment] 2019-11-04 05:41
I have no idea what the cause of the mouse polling bug was/is so it could be anything 🐸

**Comment by FurtiveDolus** [comment] 2019-11-04 05:45
Delightful. This doesn't happen in the latest Wine and D9VK. So maybe it's something Valve specifically did.

**Comment by Joshua-Ashton** [comment] 2019-11-29 00:45
Gonna close this then. Probably was the 4.11-8 FlushImplicit bug.

**Closed by Joshua-Ashton** 2019-11-29 00:45 UTC
