### ISSUE TITLE
TrackMania Nations Forever crash to desktop in the beginning [regression]

### ISSUE THREAD

**Issue by MegWATTT** [Joshua-Ashton/d9vk#235] opened 2019-07-15 20:09 UTC
Trackmania Nations Forever crash since commit 2a9a295ade671af6b6feace1d1041cec4c6c5cef. 

### Software information
Trackmania Nations Forever. The crash occurs with all possibles settings.
The game is freely available, either on Steam or by downloading it.

### System information
- GPU: AMD RX 570
- Driver: 19.1.0 + ACO
- Wine version: Wine staging 4.12.1
- D9VK version: 40f65abbb1df01f114ec98e1ffbc27f33feb9177

### Apitrace file(s)
[TmForever.110573.trim.zip](https://github.com/Joshua-Ashton/d9vk/files/3393961/TmForever.110573.trim.zip)

### Log files
- [TmForever_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3393976/TmForever_d3d9.log)

**Comment by ThisNameIsntTaken** [comment] 2019-07-16 09:33
I have the same problem.

However, the regression appears to be caused by one of the recent rebases.

Build #608 from https://git.froggi.es/joshua/d9vk/pipelines still works, and the `d3d9-cable-error` branch also works.

**Comment by MegWATTT** [comment] 2019-07-16 14:40
As I mentioned earlier, TrackMania works fine before commit 2a9a295ade671af6b6feace1d1041cec4c6c5cef and crash after this.

**Comment by K0bin** [comment] 2019-07-16 14:44
Are you sure about that? It does complain about missing a format in the logs but that's not the removed R8G8B8.

**Comment by MegWATTT** [comment] 2019-07-16 16:56
Yes.
Looks like Gallium Nine also added [support for this format due to issues with the same game](https://cgit.freedesktop.org/mesa/mesa/commit/?id=eeeab8d6b48ff83c0f42480fcd43031c34bda33f)

**Comment by ThisNameIsntTaken** [comment] 2019-07-16 18:27
I did some testing on my laptop as well. The game still works on NVIDIA on latest master. On the other hand, it crashes on Intel, AMDVLK and RADV.

**Comment by MegWATTT** [comment] 2019-07-16 19:20
Indeed. I juste set `d3d9.customVendorId = 10de` so the GPU is identified as Nvidia and it worked. Looks like the game doesn't use R8B8G8 if it detects a Nvidia GPU.

**Comment by ThisNameIsntTaken** [comment] 2019-07-19 14:38
Vendor spoofing doesn't really seem to be an optimal solution, aside from the incorrectly rendered transparent and menu objects, the game also has crashing issues on AMD (works fine on NVIDIA).

An easy way to reproduce this crash is to go to solo mode and start the A04-Acrobatic level, once that's done, go back to the menu and try to start any other level. The game will crash instantly.

This issue is even more apparent in the premium version (TrackMania United Forever) of the game. Playing a stadium level, then playing a level from any other environment will produce the same crash.

I can't provide an apitrace because the game crashes with it when I try to return to the menu after playing a level.

I'll attach the log, but I can't see anything useful in there:
- [TmForever_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3411494/TmForever_d3d9.log)

**Comment by ThisNameIsntTaken** [comment] 2019-08-01 11:43
There's another regression caused by 13a9f33 which causes the game to crash, even on NVIDIA GPUs or with the above mentioned workaround.

- [TmForever_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3456473/TmForever_d3d9.log)

Reverting this commit fixes this problem.

**Comment by ThisNameIsntTaken** [comment] 2019-08-03 13:49
The initial issue on AMD and Intel appears to be caused by acf6c27.
Reverting this commit and one mentioned in the previous comment fixes all the crashing issues in the game.

**Comment by MegWATTT** [comment] 2019-08-03 19:07
I can confirm that reverting both 13a9f3382a63a16feec51d9418b1e737e66c46f7 and acf6c27e76d07bd9f8ec2b1beb7117015ef129d8 make the game playable.
As for 2a9a295ade671af6b6feace1d1041cec4c6c5cef, it can't be reverted. I can also no longer use 
git checkout prior to that commit, as D9VK no longer compiles on older commits.

**Comment by ThisNameIsntTaken** [comment] 2019-09-16 08:51
Did some testing today, the only commit that needs to be reverted to prevent crashing is acf6c27. The other one is no longer necessary.

**Comment by ThisNameIsntTaken** [comment] 2019-09-28 07:25
The game crashes on startup (with or without acf6c27 reverted) as of bac3295 and it cannot be reverted.

- [TmForever_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3665188/TmForever_d3d9.log)

**Comment by ThisNameIsntTaken** [comment] 2019-10-15 21:40
The issue seems to be fixed by the `d3d9-scratch-unsupported` branch.

**Comment by ThisNameIsntTaken** [comment] 2019-11-10 08:32
On latest master, instead of crashing, the game seems to be freezing when I start it.
This is the last line in the log:
`err:   D3D9Query: Unsupported query type 4 (from d3d9.supportVCache)`

I'm using an RX 580. I already tried spoofing vendor id's, setting the option mentioned above to False or True, but none of it made a difference.

[TmForever_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3828220/TmForever_d3d9.log)

**Comment by ThisNameIsntTaken** [comment] 2019-11-20 22:06
As of 550a563. the problem appears to be solved. The game no longer crashes or freezes after starting it.

**Closed** 2019-12-02 05:24 UTC
