### ISSUE TITLE
Far Cry → glitches with water

### ISSUE THREAD

**Issue by NerosTie** [Joshua-Ashton/d9vk#239] opened 2019-07-15 22:40 UTC
With d9vk
![](https://i.imgur.com/bvvEpXd.jpg)

### System information
GPU: Nvidia GT 730M
Driver: 430.26-9
Wine version: Proton 4.2
DXVK version: 0.13

### Apitrace file(s)
https://mega.nz/#!qrBkjA5Q!icAyBfIWJ4vdVqn8uJQ6Pl7fhqokDT6qQEJHDvhSk_w

### Log files
d3d: [FarCry-13520.log](https://github.com/Joshua-Ashton/d9vk/files/3394480/FarCry-13520.log)

**Comment by K0bin** [comment] 2019-07-15 22:53
I've looked into this at some point. The problem is probably that the TexBem instruction isn't implemented yet.

**Comment by dlshinobi** [comment] 2019-07-15 23:08
> I've looked into this at some point. The problem is probably that the TexBem instruction isn't implemented yet.

I don't think that's the case 'cause log file spews a lot of "fixme:d3d_shader:print_glsl_info_log" messages. Probably he is using wined3d or wine d3d_compiler.

P.S. The game runs fine: https://www.youtube.com/watch?v=6lQ8cMmkPzs

**Comment by NerosTie** [comment] 2019-07-15 23:22
@dlshinobi it's a video with Call of Juaez

**Comment by CartoonFan** [comment] 2019-07-16 00:36
Good job! I was going to post about this as well.

**Comment by Joshua-Ashton** [comment] 2019-07-24 03:50
https://github.com/Joshua-Ashton/d9vk/tree/dxso-texbem is WIP for the fix for this...

Doesn't seem to be perfect yet, but it's a start!

Not sure whether the other missing op is the cause of that or I have made an error in the implementation of TEXBEM.

**Comment by NerosTie** [comment] 2019-07-24 13:20
@Joshua-Ashton with #663 it crashes on loading pages (saved game or new game)

**Comment by Joshua-Ashton** [comment] 2019-07-24 13:20
663 isnt the latest, why are people using that.

**Comment by Joshua-Ashton** [comment] 2019-07-24 13:21
Use 711 https://git.froggi.es/joshua/d9vk/-/jobs/711/artifacts/download

**Comment by NerosTie** [comment] 2019-07-24 13:25
#663 from "pipelines"! So it's the same thing as #771 in "jobs". I guess.

**Comment by Joshua-Ashton** [comment] 2019-07-24 13:43
Ah ok, yeah. Use job id in future :frog:

**Comment by Joshua-Ashton** [comment] 2019-07-24 13:43
Ah ok, yeah. Use job id in future :frog:

**Comment by Joshua-Ashton** [comment] 2019-07-24 13:43
Ah ok, yeah. Use job id in future :frog:

**Comment by Joshua-Ashton** [comment] 2019-07-24 13:43
Ah ok, yeah. Use job id in future :frog:

**Comment by Joshua-Ashton** [comment] 2019-07-24 13:43
Ah ok, yeah. Use job id in future :frog:

**Comment by Joshua-Ashton** [comment] 2019-07-24 13:43
Thanks for posting this 4 times GitHub?

**Comment by NerosTie** [comment] 2019-07-25 12:27
With #725 (jobs) the water is no longer black, but it's glitchy.

![20190725142356_1](https://user-images.githubusercontent.com/4572452/61874286-50a2c100-aee8-11e9-9c41-4df0e0675dbf.jpg)

**Comment by CartoonFan** [comment] 2019-07-25 14:08
There's also a weird reflection effect looking at the surface from underwater that looks similar to the image above. I have a log and can provide a trace if needed.

[FarCry_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3431903/FarCry_d3d9.log)

GPU: Nvidia GTX 960
Driver: 430.34.0
Wine version: 4.12.1 TKG
DXVK:https://github.com/Joshua-Ashton/d9vk/commit/bc64e8e0263004908090da60b4c478a6573fe7d0
Platform: GOG

**Comment by NerosTie** [comment] 2019-09-15 12:35
![20190915142546_1](https://user-images.githubusercontent.com/4572452/64921583-4359d280-d7c5-11e9-8f52-512dce148cca.jpg)

The shadows are back and the lighting issue seems to be gone. The only remaining issue is the water.

**Comment by Joshua-Ashton** [comment] 2019-10-09 03:34
This is fixed with recent PS 1.x projection fixes.

**Closed by Joshua-Ashton** 2019-10-09 03:34 UTC
