### ISSUE TITLE
Skinning/Geometry issue in 'Sid Meier's Pirates'

### ISSUE THREAD

**Issue by mitigd** [Joshua-Ashton/d9vk#326] opened 2019-08-25 10:30 UTC
The skinning/geometry is incorrect.

Edited, for accuracy (axredneck, K0bin), as I have no background in graphics programming.

![pirates](https://user-images.githubusercontent.com/8550687/63648398-daff6000-c6f4-11e9-8753-348e54ce2ebc.png)

### Software information
Game: Sid Meier's Pirates
Settings: Default settings. You can change any of the video options but none will fix the issue.

### System information
- GPU: Nvidia 1050 GTX Ti
- Driver: NVIDIA 435.17
- Wine version: Proton 4.11-2
- DXVK version: [13f5048](https://github.com/Joshua-Ashton/d9vk/commit/13f5048c9a330452d615128c649b7c489022f20b)

### Apitrace file(s) * log and api trace taken from Windows. The issue is the same, regardless.

https://mega.nz/#!lQEjiSxb!bC6fp9Ks_fUGTXjs6_g0qUy-Uu4Hh4hfdFYi-P9xDaA

### Log files
[Pirates!_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3538008/Pirates._d3d9.log)

**Comment by axredneck** [comment] 2019-08-26 19:29
AFAIK the issue is not with textures but with skinning.

**Comment by K0bin** [comment] 2019-08-26 19:30
Yes. Either way it's not the textures but the geometry. People will call basically everything textures.

**Comment by Joshua-Ashton** [comment] 2019-12-07 00:32
Can you try as of 4bad731f472ffffa685d412dfae73e906e97d5e5?

Should be fixed now: https://git.froggi.es/joshua/d9vk/-/jobs

**Comment by mitigd** [comment] 2019-12-09 16:28
> 
> 
> Can you try as of [4bad731](https://github.com/Joshua-Ashton/d9vk/commit/4bad731f472ffffa685d412dfae73e906e97d5e5)?
> 
> Should be fixed now: https://git.froggi.es/joshua/d9vk/-/jobs

Tested and it appears to be fixed now.

**Closed** 2019-12-09 17:07 UTC
