### ISSUE TITLE
wow 1.12 with d9vk

### ISSUE THREAD

**Issue by personallib** [Joshua-Ashton/d9vk#259] opened 2019-07-22 14:43 UTC
![Снимок экрана_2019-07-18_22-03-03](https://user-images.githubusercontent.com/52075225/61641586-73e32b80-acb0-11e9-9a0a-7dc8a8702d2d.png)
![Снимок экрана_2019-07-21_11-56-53](https://user-images.githubusercontent.com/52075225/61641669-9117fa00-acb0-11e9-931d-f48129196cd8.png)

**Comment by K0bin** [comment] 2019-07-22 17:25
You've gone out of your way to remove everything in the issue template to make sure we don't have any information that would help in fixing this.

Please add logs, an apitrace, your OS, your graphics driver, your GPU, the D9VK version and everything else that was asked for in the issue template.

**Comment by Joshua-Ashton** [comment] 2019-07-22 18:09
This is a duplicate of #219

**Closed by Joshua-Ashton** 2019-07-22 18:09 UTC
