### ISSUE TITLE
The Witcher 1 incorrect mouse input on 4K

### ISSUE THREAD

**Issue by Venemo** [Joshua-Ashton/d9vk#94] opened 2019-05-11 10:35 UTC
When running the Witcher 1 on 4K resolution, the mouse input doesn't work correcty in the main menu. When you hover the mouse over a menu item, it doesn't get highlighted and you cannot click on it. Same issue is not present on 1080p. Same issue also not present when running the game with Gallium Nine.

### Software information
The Witcher 1 - latest version as downloaded from GOG

### System information
- GPU: AMD RX 570 
- Driver: RADV, mesa 19.0.3
- Wine version: wine-4.7-1.fc30.x86_64
- D9VK version: https://git.froggi.es/joshua/d9vk/pipelines/381/builds

**Comment by Joshua-Ashton** [comment] 2019-11-26 23:15
Can't reproduce. Played for a short while and never got any issues here.

Gonna close this... Feel free to re-open if you have more details you can help me repro with, but it's working fine here.

**Closed by Joshua-Ashton** 2019-11-26 23:15 UTC
