### ISSUE TITLE
Half-Life 2 unplayable

### ISSUE THREAD

**Issue by tsalwierz** [Joshua-Ashton/d9vk#9] opened 2019-04-02 20:32 UTC
Any updates in the last two days that would render half-life 2 unplayable?

This guy's half-life 2 is completely playable 2 days ago with only a couple rendering issues. Mine, not so much.

https://www.youtube.com/watch?v=HNpBncAs0Ek

https://i.imgur.com/9raWxLD.png - main menu.

Will happily provide more information if it is something on my end.

**Comment by Riesi** [comment] 2019-04-02 20:57
The problem is that d9vk currently does not support all the new and shiny feature levels of d3d9, which means you have to set some launch options. Those should be enough to make the game work:
`-sw +mat_disable_d3d9ex 1 +mat_dxlevel 90 -dxlevel 90`

**Comment by tsalwierz** [comment] 2019-04-02 21:44
That did the trick. Renders wonderfully, has issues where all map textures vanish depending on where you look. Pretty sure it's some kind of surface texture issue with vulkan.

https://i.imgur.com/EZ6Zgvt.jpg

Anyway, cool beans. Can't wait to see other games working with d9vk. Very curious on how dishonored will perform.

**Comment by TedsterTech** [comment] 2019-04-03 17:49
May I suggest you close this? (:

**Closed** 2019-04-04 00:24 UTC
