### ISSUE TITLE
GuildWars 2 Black Screen & Crash

### ISSUE THREAD

**Issue by ronoverdrive** [Joshua-Ashton/d9vk#21] opened 2019-04-12 20:10 UTC
On Windows 10 the 64bit client gets stuck on a black screen while on WINE it gets to the character select screen and crashes. The 32bit client was not tested.

### Software information
GuildWars 2 64-bit client

### System information
- GPU: Geforce GTX 980Ti (Linux), Geforce GTX 960 (Windows)
- Driver: 418.52.03 and 425.31 respectively
- Wine version: WINE-TKG 4.5 Git Master
- DXVK version: git master

### Apitrace file(s)
- [Gw2-64.7z](https://mega.nz/#!Se4D2ARb!HOZsEfV3lzwTdoAJxMmlmjO6ciZhZDWJ0292WbD8xdM)

### Log files
- d3d9.log: [Gw2-64_d3d9.log](https://pastebin.com/cXz6Yj7f)
- [wine log](https://pastebin.com/y9g18hke)
- [d3d9.log with fullscreen patch](https://pastebin.com/t7AqxAFN)

**Comment by Jrugia** [comment] 2019-04-21 18:25
The game no longer crashes using the latest build. Using the lowest settings it's able to get in game.

https://i.imgur.com/VPF2EE1.jpg

**Comment by ronoverdrive** [comment] 2019-04-21 18:48
I can get in game now, but everything even on lowest settings is a blurry mess for me to the point its still unplayable.

https://i.imgur.com/y6hWCqk.png
https://i.imgur.com/AHmLG4A.png

**Comment by Vildravn** [comment] 2019-04-21 23:08
I can also confirm the game doesn't crash anymore on 21ab453

The lighting is glitchy at the moment, flickering when the camera moves,
the mouse movement feels somewhat off,
with Depth Blur on, the game is a blurry mess,
but aside from that, I can use the highest settings, even turn on supersample and it still works :)

Great progress!
![gw022](https://user-images.githubusercontent.com/1076814/56476577-99d31700-649a-11e9-903e-6ddfb0c3ca64.jpg)
![gw023](https://user-images.githubusercontent.com/1076814/56476580-9d669e00-649a-11e9-86f8-f48b545fd914.jpg)
![gw024](https://user-images.githubusercontent.com/1076814/56476595-ab1c2380-649a-11e9-892c-93f591ed05ff.jpg)
![image](https://user-images.githubusercontent.com/1076814/56476621-00583500-649b-11e9-96bd-34b5eef8504b.png)

**Comment by ronoverdrive** [comment] 2019-04-22 00:19
Man I wish my experience was that good. Good call on the Depth Blur that cleared things up, but my perf is trash maxing out at 20FPS.

**Comment by logan001** [comment] 2019-04-22 13:21
same as @Vildravn but only 11-15 fps where i get 23 with normal wine and i think around 40 fps with windows. but at least it started to work. keep up the good job

**Comment by Vildravn** [comment] 2019-04-22 14:38
Decided to try a few more locations. Links this time to not spam this thread with too many screenshots :)
While it's not 60fps everywhere, there IS a significant difference between d9vk and no d9vk and it "feels smoother" over-all with d9vk.

**Highest settings with d9vk**
https://i.imgur.com/42klmg6.jpg
https://i.imgur.com/m6HGT6u.jpg (I think the Charr is supposed to be green :D )
https://i.imgur.com/xvAkb1s.jpg

**Tweaked settings with d9vk**
https://i.imgur.com/BfjqNjf.jpg

**Highest settings without d9vk**
https://imgur.com/2eVM8zw.jpg

**Tweaked settings without d9vk**
https://imgur.com/mqOidre.jpg

**Comment by Joshua-Ashton** [comment] 2019-04-22 17:25
@Vildravn  Did you disable logging? For lots of games thatd have a big impact at this stage of development

**Comment by Vildravn** [comment] 2019-04-22 17:55
@Joshua-Ashton Ah, good point, looks like that improved the framerate a little. Probably can't play with Supersample on with a reasonable performance everywhere but I can live with that :) If it wasn't for the flickering and some issues with the blur (The same thing as with Depth Blur on/Adaptive lighting off appears in other situations, like conversations) the game would be very playable. Amazing job! :)

**Comment by Jrugia** [comment] 2019-04-22 19:35
@Vildravn  That's some nice testing you did there, everything considered there already seems to be some form of improvement over OpenGL. 

@Joshua-Ashton Keep up the great work, I can't believe how far the project has come in such a short time.

**Comment by logan001** [comment] 2019-04-28 07:02
the light seems to be fixed.
i see no issue with depth blur anymore.
my character head is no longer translucent
but there are some rendering issues
d9vk
![Screenshot from 2019-04-28 09-05-38](https://user-images.githubusercontent.com/6472378/56859947-0f0e8280-699a-11e9-9ead-a07c97de7d26.png)

and without 
![Screenshot from 2019-04-28 09-02-16](https://user-images.githubusercontent.com/6472378/56859960-1c2b7180-699a-11e9-80aa-96f5e403279a.png)

d9vk
![Screenshot from 2019-04-28 09-54-39](https://user-images.githubusercontent.com/6472378/56860160-ebe4d280-699b-11e9-93fd-64e21d7ada4d.png)

and without 
![Screenshot from 2019-04-28 09-55-46](https://user-images.githubusercontent.com/6472378/56860165-f3a47700-699b-11e9-970c-55305c3b0c19.png)

i have no clue how to use apitrace.
[here](https://drive.google.com/open?id=1Y6iyEaieV6ubp9MSkBKsEuvAh8PEs6cr) is d3d9 logs

**Comment by yaomtc** [comment] 2019-04-29 00:56
Been testing the game today (Ryzen 1700X, RX 580). Had a few crashes, and there is the stutter. Also, the game only works with Shaders set to Low, not Medium/High. Aside from all that, though, the game works surprisingly well! Amazed to see such high max fps (never got up past 50 this often with my settings), looking forward to the kinks getting worked out and getting smooth framerates eventually!

I tried apitrace but I couldn't figure out how to use it either. [It does have instructions](https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown), but first I'd need to figure out how to run Wine with D9VK from the terminal and switch it off and on... I've been using Lutris for that, and putting the apitrace command into "command prefix" doesn't work.

**Comment by Joshua-Ashton** [comment] 2019-04-29 00:57
@logan001  Can you check if the texture alpha/cutout issues are fixed in latest for you?

**Comment by yaomtc** [comment] 2019-04-29 01:41
I think so far all the crashes I've had happened shortly after entering one of the newer maps, in the Crystal Desert region in particular. "Map load hang on STATE_MODELS_STREAM detected" is I think what caused the crash, maybe, see [gw2-crash-dump.txt](https://github.com/Joshua-Ashton/d9vk/files/3125766/gw2-crash-dump.txt)

**Comment by ReaperOfSouls1909** [comment] 2019-04-29 01:42
Testing now

**Comment by ReaperOfSouls1909** [comment] 2019-04-29 01:45
![image](https://user-images.githubusercontent.com/18043258/56873221-3d767700-6a07-11e9-8dbb-36f41dfd1733.png)
new maps work fine

**Comment by logan001** [comment] 2019-04-29 06:14
> @logan001 Can you check if the texture alpha/cutout issues are fixed in latest for you?

the problem is almost fixed.
the alpha seems to have some problems on HoT maps.
i've made a trace. You can download it from [here](https://drive.google.com/open?id=19cp7LBT6NDsTXdl9S-FHYRlmb5z598VZ)

**Comment by logan001** [comment] 2019-04-29 07:36
> Been testing the game today (Ryzen 1700X, RX 580). Had a few crashes, and there is the stutter. Also, the game only works with Shaders set to Low, not Medium/High. Aside from all that, though, the game works surprisingly well! Amazed to see such high max fps (never got up past 50 this often with my settings), looking forward to the kinks getting worked out and getting smooth framerates eventually!
> 
> I tried apitrace but I couldn't figure out how to use it either. [It does have instructions](https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown), but first I'd need to figure out how to run Wine with D9VK from the terminal and switch it off and on... I've been using Lutris for that, and putting the apitrace command into "command prefix" doesn't work.

probably the video driver is the issue. seems that nvidia has no problem with this game. try both drivers (open/close) for ati. from what i can understand proprietary ati drivers has better vulkan support than mesa drivers.

to add d9vk to wine prefix i do this (for every new d9vk i download)
`env WINEPREFIX=~/winetestNN winecfg`
to create all wine folders/etc in home folder. 
then
`env WINEPREFIX=~/winetestNN ./setup_dxvk.sh install`
to add d9vk to the new wineprefix
then
`env WINEPREFIX=~/winetestNN DXVK_HUD=full wine64 /path/to/Gw2-64.exe`
you can adjusts the paths as you wish.
for apitrace took me a while to figure it out
you have to download windows binaries (there is a link on the git page to download msvc binaries)
than run the game like `wine /path/to/32or64bits/apitrace.exe trace -a d3d9 /path/to/game.exe`
to continue the exeample
`env WINEPREFIX=~/winetestNN DXVK_HUD=full wine64 /path/to/64bits/apitrace.exe trace -a d3d9 /path/to/Gw2-64.exe`

**Comment by logan001** [comment] 2019-05-03 18:52
finally the ground texture is fixed (ab57adc)
also i think there is 2-3 fps more on that complex map and more on character selection screeen
of course is still way slower than normal wine. FOR NOW.

now the alpha problem is still there for some textures.
![Screenshot from 2019-05-03 21-39-52](https://user-images.githubusercontent.com/6472378/57158814-fca6a580-6dec-11e9-9c5c-918675c0e0c2.png)
Those leafs has 2 alpha textures? im not sure. one on top that renders well and another on the buttom that does not work as i marked on the image. 
i thought that this kind of problem is only on HoT maps but there are other places in old maps that has same problem. not as many as HoT maps

**Comment by Tk-Glitch** [comment] 2019-05-03 19:47
@logan001 What do you mean by `of course is still way slower than normal wine`?
What's slower? I mean, on my hardware I get ~50fps avg with wined3d and ~140 with D9VK. Did you disable logging? If you didn't, you might want to export `DXVK_LOG_LEVEL=none`.

**Comment by logan001** [comment] 2019-05-03 20:13
i get 25 fps normal wine staging and 15 fps d9vk (as you can see on the screenshot and thst is not looking on the hole valley)
these fps are at best appearance and uncheck the depth blur effect full screen (1920x1080).
of course i get higher fps on less demanding maps but not that high. around 30-35fps at most with d9vk.
DXVK_LOG_LEVEL=none has no effect or i can't see any effect on fps in hud.
l'm using wine staging 4.7 standard from wine repos on linuxmint cinnamon.

**Comment by ReaperOfSouls1909** [comment] 2019-05-03 20:21
![image](https://user-images.githubusercontent.com/18043258/57163547-e89c7d00-6dc7-11e9-8605-e9026861985a.png)
can confirm speeds that tkg said just disable logging

**Comment by Tk-Glitch** [comment] 2019-05-03 20:35
@logan001 That sounds very wrong that you're seeing no difference. Logging is enabled by default in D9VK for now and can easily eat 70%+ of your frames on some games at this point.

**Comment by ReaperOfSouls1909** [comment] 2019-05-03 20:54
sounds like a wine bug the one i had on arch where gw2 is ultra slow

**Comment by logan001** [comment] 2019-05-03 21:06
well i'm on arch now and i have same fps.
no difference with or without logs.
any other suggestions are welcome
i thought that maybe my graphic card its working on lower pcie speed but nvidia report gen3 16x. nothing wrong there.
on arch i have newer version (418.52.03) of beta driver than on linuxmint. but the performance are the same

**Comment by Joshua-Ashton** [comment] 2019-05-03 21:08
> 
> 
> well i'm on arch now and i have same fps.
> no difference with or without logs.
> any other suggestions are welcome
> i thought that maybe my graphic card its working on lower pcie speed but nvidia report gen3 16x. nothing wrong there.
> on arch i have newer version (418.52.03) of beta driver than on linuxmint. but the performance are the same

Any specs of your system?

**Comment by ReaperOfSouls1909** [comment] 2019-05-03 21:08
i fixed my issue by wiping out wine and reinstalling then i redownloaded the game

**Comment by Joshua-Ashton** [comment] 2019-05-03 21:14
Yeah, maybe also try deleting your state cache

**Comment by logan001** [comment] 2019-05-03 21:16
r7-1700x (no overclock)
32 gb ram at 3Ghz
970 GTX
nvme disk for linuxmint
sata 3 ssd for arch
i just realize something. my game is on ntfs partition (same ssd as arch). now i'm copying it on ext4 partition. not sure if this changes anything.

**Comment by Joshua-Ashton** [comment] 2019-05-03 21:24
> 
> 
> r7-1700x (no overclock)
> 32 gb ram at 3Ghz
> 970 GTX
> nvme disk for linuxmint
> sata 3 ssd for arch
> i just realize something. my game is on ntfs partition (same ssd as arch). now i'm copying it on ext4 partition. not sure if this changes anything.

Also, please move this to a new issue given GW2 seems to be working now. :)

**Closed by Joshua-Ashton** 2019-05-03 21:24 UTC

**Comment by Dante4** [comment] 2019-06-21 13:31
Unsure if this support Windows, but i don't know why it shouldn't, taking in account required of Wine, so i will post it there. Game crash on startup after 2 sec into character select menu. No matter what i do (move mouse, click to log in to character, switch characters) it crashes after 2 sec with memory problem (i.e. 0xc0000005)


### Software information
Maximum Appearance (i.e. everything on Ultra or High) and Windowed Borderless as resolution 

### System information
- GPU: Nvidia Geforce GTX 1060 6GB
- Driver: 398.36
- Wine version: No wine, but Windows 7 Pro x64 
- DXVK version: https://git.froggi.es/joshua/d9vk/-/jobs/565

### Log files
[Gw2-64_d3d9.log](https://github.com/Joshua-Ashton/d9vk/files/3314601/Gw2-64_d3d9.log)
[gw2 crash report.txt](https://github.com/Joshua-Ashton/d9vk/files/3314606/gw2.crash.report.txt)

**Comment by Joshua-Ashton** [comment] 2019-06-21 13:49
Weird, some people reported this as working recently.
Have you updated ARCDPS recently? Can you try an older version?

**Comment by GloriousEggroll** [comment] 2019-06-21 15:15
ArcdDPS is working fine here in Wine +D9VK, Vega VII, Latest version of d9vk fixed-function branch and latest version of ArcDPS from Jun 11.

![arcdps](https://user-images.githubusercontent.com/11287837/59932729-12a41000-9405-11e9-939c-24928b7e2859.png)

**Comment by DxCx** [comment] 2019-06-21 15:24
same setup as @GloriousEggroll , works for me too =)
Thanks @Joshua-Ashton =)

**Comment by Dante4** [comment] 2019-06-21 15:53
> Weird, some people reported this as working recently.
> Have you updated ARCDPS recently? Can you try an older version?

The problem is that game crashes with just d9vk. Without ArcDPS or anything else

**Comment by Joshua-Ashton** [comment] 2019-06-21 15:55
idk, people have been using it w/ Windows for a while too.

You do have a working Vulkan driver, right?

**Comment by Dante4** [comment] 2019-06-21 15:59
> idk, people have been using it w/ Windows for a while too.

Then any possibility why game crashes on certain time mark? Tried version linked on reddit (jobs/563) same result

**Comment by GloriousEggroll** [comment] 2019-06-21 18:38
D9VK without arcdps also works fine for me in Wine

**Comment by Dante4** [comment] 2019-06-21 18:42
> D9VK without arcdps also works fine for me in Wine
Again. Wine is not fully windows. And Windows is not fully wine. That's my problem. I can read and know that this works fine in Wine environment.

**Comment by GloriousEggroll** [comment] 2019-06-21 20:23
That's great that you know how to read, however it still needs to be specified that this issue is related to d9vk and windows, and is unrelated to arcdps and wine, in order to narrow down the problem.  My comments were to clarify what particular setup does work so that we know it's not entirely broken. Feel free to take your attitude elsewhere.

**Comment by Dante4** [comment] 2019-06-21 20:39
> My comments were to clarify what particular setup does work so that we know it's not entirely broken.

What I tried to say is that it's problem with mine setup. We do know that this is working with GW2 with wine, because of screenshots just up there. We also know this is working with ArcDPS with Wine from reddit. So the problem is somewhere that's not Wine or ArcDPS. That's why i don't understand reasons behind your message.

**Comment by GloriousEggroll** [comment] 2019-06-21 20:46
This.is.not.reddit.

**Comment by Joshua-Ashton** [comment] 2019-06-21 20:51
Guys, chill out.

I've had someone else test this out and it works fine for them (they were AMD however.)

Looks like it could be your driver? (I have no idea how Windows' NV driver versioning works) so I'd make sure you're up to date on that.

**Comment by Dante4** [comment] 2019-06-21 21:08
> I have no idea how Windows' NV driver versioning works

As far as i read my driver's version support Vulkan 1.1 (http://us.download.nvidia.com/Windows/398.36/398.36-win10-win8-win7-desktop-release-notes.pdf), that's right version, right?

**Comment by Joshua-Ashton** [comment] 2019-06-21 21:11
The Vulkan version is a completely irrelevant and worthless number.

Your driver looks to be out of date. Please update it if necessary and try again.

**Comment by Dante4** [comment] 2019-06-21 21:15
> Your driver is massively out of date. Please update it and try again.

Is this absolutely need?

**Comment by Joshua-Ashton** [comment] 2019-06-21 21:19
Nobody else is experiencing your issue, and they're all on *much* newer drivers.

I'm not going to look into the issue at all unless I can confirm it's a problem with your setup. Is there a reason you need **year old** drivers?

**Comment by Dante4** [comment] 2019-06-21 21:22
> I'm not going to look into the issue at all if I can confirm it's a problem with your setup, so I'd like to eliminate that.

Ok, i will update my drivers after raiding (10-20 mins) to eliminate this probability. Still unsure how this could affect this plugin.

> Is there a reason you need **year old** drivers?

Only two. First is that Nvidia added Spectre\Meltdown patch to their drivers in never versions. Second, MHW is lagging on my PC with newer drivers.

**Comment by Joshua-Ashton** [comment] 2019-06-21 21:26
Well, if that turns out to be the case, I cannot tell you how much I do not care about supporting year old drivers.

**Comment by Dante4** [comment] 2019-06-21 21:37
Yes, dumb question. But, aren't Vulkan API should be the same across all version (after it included) or dxvk use some specific function that was implemented later?

**Comment by Joshua-Ashton** [comment] 2019-06-21 21:44
No, because of extensions.

Additionally, drivers get updates to fix issues, hence why I am telling you now *for the fourth time* to update your drivers as this issue affects nobody else I know who are all using newer drivers.

**Comment by Dante4** [comment] 2019-06-21 21:49
> No, because of extensions.

So dxvk use some specific functions that was implemented later?

**Comment by Joshua-Ashton** [comment] 2019-06-21 21:51
Indeed.

**Comment by Dante4** [comment] 2019-06-21 21:54
Ah, so that's how it is. Well. I'm updating right now. If this fix it, would be great.

**Comment by Dante4** [comment] 2019-06-21 22:08
Welp. Indeed problem with my driver's version. Guess I need to choose what I wanna more.

**Comment by GloriousEggroll** [comment] 2019-06-21 23:53
Per the README:

Notes on Vulkan drivers

Before reporting an issue, please check the Wiki page on the current driver status and make sure you run a recent enough driver version for your hardware.


Per the WIKI:

https://github.com/doitsujin/dxvk/wiki/Driver-support

Where idiots are lacking, reddit provides apparently.

**Comment by Dante4** [comment] 2019-06-23 09:41
> Per the README:

As you could notice it said "No support for Windows drivers", so why did you linked it?

**Comment by Joshua-Ashton** [comment] 2019-06-23 12:58
Upstream may not care about supporting Windows building/drivers -- but I do.

Either way, the recommended driver version for Linux is at least going to apply to Windows too for obvious reasons.

**Comment by GloriousEggroll** [comment] 2019-06-23 19:16
> > Per the README:
> 
> As you could notice it sais "No support for Windows drivers", so why did you linked it? And here i thought ppl can read before link something...

If you were capable of reading you would've seen "No support for Windows drivers" before even posting, and it would not have taken someone telling you FOUR TIMES to update your drivers before actually getting something unsupported to even work.
